In [1]:
import pandas as pd

In [2]:
path = '/itf-fi-ml/shared/users/ziyuzh/svm/data/pre_processed_features/expression_emb/gene2vec_dim_200_iter_9.txt'

# Read the data from the text file
with open(path, 'r') as file:
    lines = file.readlines()

# Create a dictionary to store the data
data_dict = {}

# Loop through each line and capture the information in the dictionary
for line in lines:
    parts = line.strip().split('\t')
    key = parts[0]
    values = list(map(float, parts[1].split()))
    data_dict[key] = values

# Convert the dictionary to a DataFrame
df = pd.DataFrame.from_dict(data_dict, orient='index')

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
PLAC4,-0.032111,0.005355,-0.001208,0.392700,0.027191,0.057858,-0.065911,0.256802,0.043661,0.081228,...,0.179668,0.199858,-0.044920,0.095846,0.041332,-0.147439,0.239312,-0.183174,-0.264830,0.104818
RPS2P45,-0.433589,0.383065,0.154259,-0.044726,0.406748,0.089424,0.186105,-0.038986,0.245488,-0.712083,...,0.079383,-0.028575,0.263809,0.177087,-0.015819,0.120731,-0.219403,0.199372,0.101292,-0.054681
C3orf18,0.030009,-0.283322,0.213689,0.084640,-0.012634,-0.288767,-0.004061,-0.089572,0.249219,0.164836,...,0.037768,0.328689,0.064318,0.026143,0.005801,-0.185695,0.067693,-0.246346,-0.120931,0.157672
C6orf226,0.029573,-0.058847,-0.297716,0.257432,0.062723,0.071785,-0.079403,0.420420,0.219320,0.316385,...,0.243931,-0.075696,0.092758,0.093465,-0.191904,-0.286557,-0.140394,-0.159963,-0.223003,0.250665
CISD3,0.148815,-0.100394,0.139844,-0.156749,-0.000815,0.115267,0.101778,0.158580,0.287842,0.049861,...,0.227863,0.086968,0.062115,0.314489,-0.148824,-0.121338,-0.245106,0.247893,-0.034497,0.038109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LOC284219,-0.097413,0.206977,0.274137,-0.052645,-0.163830,0.080587,0.147385,-0.081156,-0.100284,0.190910,...,0.516521,-0.356231,0.259438,-0.353476,-0.510408,0.158663,-0.378703,-0.184715,0.041767,0.065761
KRTAP21-1,0.093780,-0.661438,0.342262,-0.742463,-0.402170,0.172066,1.039949,-0.706364,1.170597,-0.120575,...,-0.046443,0.347276,1.131234,0.249182,0.902638,0.147042,0.445153,-0.163675,-0.148416,0.195759
PHBP8,-0.491280,-0.335584,-0.454166,-0.134393,-0.455670,-0.137623,-0.335810,-0.065315,-0.172522,-0.110279,...,0.743257,0.116302,0.027702,-0.351308,0.163348,-0.089611,-0.345655,-0.071142,0.027078,0.223668
KCNE1L,-0.103615,0.133627,-0.156624,0.134105,-0.226790,-0.120270,0.161322,-0.165074,-0.041661,-0.313059,...,0.022152,-0.699078,0.035016,-0.788035,-0.045039,-0.304939,0.130196,0.361877,0.190919,0.649156
LOC101928725,-0.179048,0.241712,-0.074082,-0.137115,0.160695,-0.034816,0.205781,0.063766,-0.600309,-0.225615,...,0.101723,0.184042,0.120395,0.157748,-0.170004,0.337413,0.421538,-0.103381,-0.307587,-0.053007

In [ ]:
dtring_uniport = pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/uniport_id/idmapping_string.tsv', sep='\t')

In [11]:
dtring_uniport_map = dict(zip(dtring_uniport['From'], dtring_uniport['Entry']))

In [8]:
ppi= pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/ppi_full_2019_emb.csv')

In [12]:
ppi['uniport'] = ppi['string_id'].map(dtring_uniport_map)

In [13]:
ppi[ppi['uniport'].isna()]

,string_id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_120,feature_121,feature_122,feature_123,feature_124,feature_125,feature_126,feature_127,feature_128,uniport
6,9606.ENSP00000400088,-0.004529,0.292238,-0.011465,0.010524,-0.067736,0.110694,0.234754,0.163985,0.093332,...,-0.206243,-0.178106,-0.225745,-0.083765,-0.080485,-0.082826,0.019327,0.054980,-0.073713,NaN
12,9606.ENSP00000284957,-0.052902,-0.294304,-0.272006,0.100091,0.031358,0.087290,-0.002054,0.098753,-0.062649,...,-0.169028,-0.034665,-0.074272,0.145135,-0.299570,-0.006395,-0.048642,-0.349602,0.155795,NaN
13,9606.ENSP00000332668,-0.218763,0.017556,-0.156147,-0.012632,-0.160411,-0.131807,0.277137,0.350353,-0.031442,...,-0.127082,-0.356447,-0.060170,-0.150267,0.013439,0.086310,-0.002981,-0.046666,-0.043220,NaN
14,9606.ENSP00000371734,-0.020228,0.149380,-0.259822,-0.076778,-0.019141,-0.032650,0.141752,0.231568,0.159790,...,-0.090155,-0.183542,-0.173242,-0.070528,-0.033166,-0.213442,0.062626,0.084582,0.048967,NaN
17,9606.ENSP00000270451,-0.055665,0.099913,-0.171350,0.055901,-0.165952,0.043509,0.079982,0.326638,0.078510,...,-0.080198,-0.268616,-0.299734,0.042862,0.092131,0.350034,-0.039824,0.271941,-0.089156,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19571,9606.ENSP00000385884,0.169497,-0.130221,0.021375,0.089994,-0.153267,-0.394312,0.186672,0.293803,0.495581,...,-0.331790,-0.012530,-0.337074,-0.045786,0.136962,-0.281244,-0.159979,0.164129,0.196267,NaN
19572,9606.ENSP00000447146,0.115104,-0.018336,-0.104577,0.204167,-0.350116,-0.212508,0.185143,-0.140782,0.083493,...,-0.158061,-0.080496,-0.195382,-0.128152,-0.288858,-0.189222,-0.115754,0.011692,0.305442,NaN
19573,9606.ENSP00000451052,-0.166956,0.143149,-0.085259,0.073287,-0.104302,-0.086628,0.080904,0.175583,0.049591,...,-0.049025,-0.100909,-0.407753,0.099491,0.149086,-0.067398,0.030971,0.014773,-0.164685,NaN
19574,9606.ENSP00000434593,0.400211,-0.019809,0.025966,0.007134,-0.272764,-0.322921,-0.024728,-0.286814,0.329120,...,0.450379,0.003466,0.136351,-0.300367,-0.085171,-0.170955,0.215977,0.136474,0.009883,NaN
19575,9606.ENSP00000469112,0.053946,-0.083705,-0.172060,0.155646,0.074347,-0.284910,0.206715,-0.038088,-0.193566,...,0.185505,-0.135379,-0.212421,-0.155777,-0.154464,-0.294759,0.045350,0.065805,0.196365,NaN

In [21]:
import pickle
with open('/itf-fi-ml/shared/users/ziyuzh/svm/data/stringdb/2023/name_convert.pkl', 'rb') as file:
    loaded_data = pickle.load(file)
stringId2name,name2stringId,aliases2stringId = loaded_data

In [19]:
len(stringId2name)

19699

In [22]:
name2stringId['CDK3']

'9606.ENSP00000410561'

In [23]:
ppi[ppi['string_id']=='9606.ENSP00000410561']

Empty DataFrame
Columns: [string_id, feature_1, feature_2, feature_3, feature_4, feature_5, feature_6, feature_7, feature_8, feature_9, feature_10, feature_11, feature_12, feature_13, feature_14, feature_15, feature_16, feature_17, feature_18, feature_19, feature_20, feature_21, feature_22, feature_23, feature_24, feature_25, feature_26, feature_27, feature_28, feature_29, feature_30, feature_31, feature_32, feature_33, feature_34, feature_35, feature_36, feature_37, feature_38, feature_39, feature_40, feature_41, feature_42, feature_43, feature_44, feature_45, feature_46, feature_47, feature_48, feature_49, feature_50, feature_51, feature_52, feature_53, feature_54, feature_55, feature_56, feature_57, feature_58, feature_59, feature_60, feature_61, feature_62, feature_63, feature_64, feature_65, feature_66, feature_67, feature_68, feature_69, feature_70, feature_71, feature_72, feature_73, feature_74, feature_75, feature_76, feature_77, feature_78, feature_79, feature_80, feature_81, feature_82, feature_83, feature_84, feature_85, feature_86, feature_87, feature_88, feature_89, feature_90, feature_91, feature_92, feature_93, feature_94, feature_95, feature_96, feature_97, feature_98, feature_99, ...]
Index: []

[0 rows x 130 columns]

In [20]:
len(ppi)

19576

In [3]:
import os
local_stringdb = os.path.join('/itf-fi-ml/shared/users/ziyuzh/svm/data/stringdb','2023')

ppidf = pd.read_csv(os.path.join(local_stringdb,'9606.protein.info.v12.0.txt'), sep='\t', header=0, usecols=['#string_protein_id', 'preferred_name'])
ppidf['preferred_name'] = ppidf['preferred_name'].str.upper()
stringId2name = ppidf.set_index('#string_protein_id')['preferred_name'].to_dict()
name2stringId = ppidf.set_index('preferred_name')['#string_protein_id'].to_dict()
ppidf = pd.read_csv(os.path.join(local_stringdb,'9606.protein.aliases.v12.0.txt'), sep='\t', header=0, usecols=['#string_protein_id', 'alias']).drop_duplicates(['alias'], keep='first')
ppidf['alias'] = ppidf['alias'].str.upper()
aliases2stringId = ppidf.set_index('alias')['#string_protein_id'].to_dict()

def string_convert(gene):
    if gene in name2stringId.keys():
        return name2stringId[gene]
    elif gene in aliases2stringId.keys():
        return aliases2stringId[gene]
    else:
        return None

In [4]:
df.shape

(24447, 200)

In [5]:
string_dict = dict()
for gene in df.index.tolist():
    string_dict[gene] = string_convert(gene)
df['string_id'] = df.index.map(string_dict)
df.shape

(24447, 201)

In [19]:
df[~df['string_id'].isna()]['string_id'].nunique()

17481

In [6]:
df = df.dropna(subset='string_id')
len(df)

17622

In [7]:
df_unique = df.drop_duplicates(subset='string_id')
len(df_unique)

17481

In [8]:
# Assuming you have a DataFrame df and a dictionary name2stringId
# Find duplicated rows based on 'string_id'
duplicated_rows = df[df.duplicated(subset='string_id', keep=False)]

# Filter rows based on the condition
rows_to_keep = duplicated_rows.index.isin(name2stringId.keys())

# Create a new DataFrame with the rows to keep
df_filtered = duplicated_rows[rows_to_keep]

# If you want to remove these from the original df:
df = df.drop(df.index.difference(df_filtered.index))

# Alternatively, if you want only the remaining DataFrame:
# df_filtered will be your final DataFrame with rows you want to keep

In [9]:
len(df)

95

In [10]:
df_combined = pd.concat([df_unique, df], axis=0)
len(df_combined)

17576

In [11]:
df_combined.head(3)

,0,1,2,3,4,5,6,7,8,9,...,191,192,193,194,195,196,197,198,199,string_id
CISD3,0.148815,-0.100394,0.139844,-0.156749,-0.000815,0.115267,0.101778,0.158580,0.287842,0.049861,...,0.086968,0.062115,0.314489,-0.148824,-0.121338,-0.245106,0.247893,-0.034497,0.038109,9606.ENSP00000483781
KDM1A,-0.037154,0.038770,-0.100821,0.165520,0.324188,0.095911,0.090766,0.336213,0.334166,-0.296031,...,-0.252097,0.266917,-0.333782,-0.011449,0.064207,0.033128,0.222754,0.234885,-0.410366,9606.ENSP00000383042
HIST1H2BN,-0.293039,-0.049834,-0.074517,-0.003607,0.067420,-0.154789,0.113428,-0.114366,0.048271,0.186912,...,0.056385,0.146475,-0.034893,0.039808,-0.165166,0.168566,-0.207136,-0.079345,0.191214,9606.ENSP00000483903

In [12]:
new_columns = ['string_id'] + [f'feature_{i}' for i, col in enumerate(df_combined.columns) if col != 'string_id']

# Reorder the DataFrame so that 'string_id' is the first column
df_combined = df_combined[['string_id'] + [col for col in df_combined.columns if col != 'string_id']]
df_combined.columns = new_columns

df_combined.head(2)

,string_id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,...,feature_190,feature_191,feature_192,feature_193,feature_194,feature_195,feature_196,feature_197,feature_198,feature_199
CISD3,9606.ENSP00000483781,0.148815,-0.100394,0.139844,-0.156749,-0.000815,0.115267,0.101778,0.158580,0.287842,...,0.227863,0.086968,0.062115,0.314489,-0.148824,-0.121338,-0.245106,0.247893,-0.034497,0.038109
KDM1A,9606.ENSP00000383042,-0.037154,0.038770,-0.100821,0.165520,0.324188,0.095911,0.090766,0.336213,0.334166,...,0.209735,-0.252097,0.266917,-0.333782,-0.011449,0.064207,0.033128,0.222754,0.234885,-0.410366

In [13]:
df_combined.to_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/pre_processed_features/expression_emb/exp_emb.csv',index=False)