In [1]:
import pandas as pd
import numpy as np
import gseapy as gp
import pickle
import mygene

In [5]:
for i in gp.get_library_name(organism='Human'):
    if '2019' in i.lower():
        print(i)

BioPlanet_2019
ClinVar_2019
DepMap_WG_CRISPR_Screens_Broad_CellLines_2019
DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019
GWAS_Catalog_2019
InterPro_Domains_2019
KEGG_2019_Human
KEGG_2019_Mouse
Pfam_Domains_2019
PheWeb_2019
TRRUST_Transcription_Factors_2019
WikiPathways_2019_Human
WikiPathways_2019_Mouse

In [11]:
def to_pathway_df(db):
    keggs_2019 =gp.get_library(name=db,organism='human')
    all_genes = sorted(set(g for genes in keggs_2019.values() for g in genes))

    # create matrix
    df = pd.DataFrame(0, index=all_genes, columns=keggs_2019.keys())
    for col, genes in keggs_2019.items():
        df.loc[genes, col] = 1
    return df

In [14]:
df = to_pathway_df('KEGG_2019_Human')
df.shape

(7802, 308)

In [12]:
wiki_df = to_pathway_df('WikiPathways_2019_Human')

In [13]:
wiki_df.shape

(6201, 472)

In [15]:
ppi = pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/stringdb/uniport_ppi_2019.csv')

In [16]:
ppi.head(3)

,string_id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_119,feature_120,feature_121,feature_122,feature_123,feature_124,feature_125,feature_126,feature_127,feature_128
0,P84085,-0.188154,0.192034,0.021007,-0.115466,-0.106862,0.001464,0.079977,0.308825,-0.013989,...,0.163154,0.025956,-0.154160,0.047249,0.013052,-0.121823,0.261028,0.076985,0.027698,0.038653
1,P05129,-0.056868,0.169329,-0.159240,0.109760,-0.025587,0.082301,0.017834,0.020714,-0.020855,...,0.243663,-0.131249,-0.205958,-0.202946,-0.267179,-0.182676,-0.227924,0.124403,-0.201234,-0.194766
2,Q9UQR1,-0.055811,0.039503,0.155353,0.067647,0.073602,0.088512,0.010504,0.194107,0.187011,...,-0.076926,-0.093258,-0.206983,-0.309286,0.032149,0.053479,0.090693,0.144785,0.106935,0.007952

In [17]:

mg = mygene.MyGeneInfo()
# Query mygene for UniProt and Entrez gene ID mappings
results = mg.querymany(
    df.index.tolist(),
    scopes='symbol',
    fields='uniprot,entrezgene',
    species='human'
)

WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
INFO:biothings.client:querying 1-1000 ...
INFO:biothings.client:querying 1001-2000 ...
INFO:biothings.client:querying 2001-3000 ...
INFO:biothings.client:querying 3001-4000 ...
INFO:biothings.client:querying 4001-5000 ...
INFO:biothings.client:querying 5001-6000 ...
INFO:biothings.client:querying 6001-7000 ...
INFO:biothings.client:querying 7001-7802 ...
INFO:biothings.client:Finished.
WARNING:biothings.client:21 input query terms found dup hits:	[('BIRC8', 2), ('BORCS8-MEF2B', 2), ('BUB1B-PAK6', 2), ('DHRS4L1', 3), ('FCGR2C', 2), ('KLRC4-KLRK1'
WARNING:biothings.client:185 input query terms found no hit:	['AARS', 'ADSS', 'ADSSL1', 'ARNTL', 'ATP6', 'ATP8', 'BVES', 'CARD17', 'CARS', 'CBSL', 'CIR1', 'COX1'
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [18]:
results_df = pd.DataFrame(results)
results_df = results_df[~results_df['entrezgene'].isna()]
results_df['uniprot_ids'] = results_df['uniprot'].apply(
    lambda x: list(x.values())[0] if isinstance(x, dict) and 'Swiss-Prot' in x else None)
results_df = results_df[~results_df['uniprot_ids'].isna()]
results_df[results_df['uniprot_ids'].apply(lambda x: isinstance(x, list) and len(x) > 1)]

,query,_id,_score,entrezgene,uniprot,notfound,uniprot_ids
329,AMY1A,276,25.374277,276,"{'Swiss-Prot': ['P0DTE7', 'P0DUB6', 'P0DTE8'],...",NaN,"[P0DTE7, P0DUB6, P0DTE8]"
330,AMY1B,277,27.387224,277,"{'Swiss-Prot': ['P0DTE7', 'P0DUB6', 'P0DTE8'],...",NaN,"[P0DTE7, P0DUB6, P0DTE8]"
331,AMY1C,278,22.482887,278,"{'Swiss-Prot': ['P0DTE7', 'P0DUB6', 'P0DTE8'],...",NaN,"[P0DTE7, P0DUB6, P0DTE8]"
644,BBC3,27113,18.347180,27113,"{'Swiss-Prot': ['Q9BXH1', 'Q96PG8']}",NaN,"[Q9BXH1, Q96PG8]"
761,C4B,721,19.491293,721,"{'Swiss-Prot': ['P0C0L5', 'P0C0L4'], 'TrEMBL':...",NaN,"[P0C0L5, P0C0L4]"
819,CALCA,796,18.890875,796,"{'Swiss-Prot': ['P01258', 'P06881']}",NaN,"[P01258, P06881]"
826,CALM1,801,18.288290,801,"{'Swiss-Prot': ['P0DP24', 'P0DP23', 'P0DP25'],...",NaN,"[P0DP24, P0DP23, P0DP25]"
827,CALM2,805,18.274733,805,"{'Swiss-Prot': ['P0DP24', 'P0DP23', 'P0DP25'],...",NaN,"[P0DP24, P0DP23, P0DP25]"
828,CALM3,808,18.869629,808,"{'Swiss-Prot': ['P0DP24', 'P0DP23', 'P0DP25'],...",NaN,"[P0DP24, P0DP23, P0DP25]"
923,CCL4L1,388372,26.595705,388372,"{'Swiss-Prot': ['P13236', 'Q8NHW4'], 'TrEMBL':...",NaN,"[P13236, Q8NHW4]"
1054,CDKN2A,1029,21.375517,1029,"{'Swiss-Prot': ['P42771', 'Q8N726'], 'TrEMBL':...",NaN,"[P42771, Q8N726]"
2014,ERCC6,2074,17.575155,2074,"{'Swiss-Prot': ['P0DP91', 'Q03468'], 'TrEMBL':...",NaN,"[P0DP91, Q03468]"
2487,GNAS,2778,17.821873,2778,"{'Swiss-Prot': ['Q5JWF2', 'P84996', 'P63092', ...",NaN,"[Q5JWF2, P84996, P63092, O95467]"
2941,HSPA1A,3303,22.000189,3303,"{'Swiss-Prot': ['P0DMV9', 'P0DMV8'], 'TrEMBL':...",NaN,"[P0DMV9, P0DMV8]"
2942,HSPA1B,3304,19.300636,3304,"{'Swiss-Prot': ['P0DMV9', 'P0DMV8'], 'TrEMBL':...",NaN,"[P0DMV9, P0DMV8]"
3947,MOCS2,4338,17.964008,4338,"{'Swiss-Prot': ['O96007', 'O96033'], 'TrEMBL':...",NaN,"[O96007, O96033]"
4118,NACA,4666,17.826088,4666,"{'Swiss-Prot': ['Q13765', 'E9PAV3'], 'TrEMBL':...",NaN,"[Q13765, E9PAV3]"
4365,NPY4R2,100996758,19.823011,100996758,"{'Swiss-Prot': ['P50391', 'P0DQD5']}",NaN,"[P50391, P0DQD5]"
4390,NRXN1,9378,18.248740,9378,"{'Swiss-Prot': ['P58400', 'Q9ULB1'], 'TrEMBL':...",NaN,"[P58400, Q9ULB1]"
4391,NRXN2,9379,18.674417,9379,"{'Swiss-Prot': ['P58401', 'Q9P2S2'], 'TrEMBL':...",NaN,"[P58401, Q9P2S2]"
4392,NRXN3,9369,18.271637,9369,"{'Swiss-Prot': ['Q9HDB5', 'Q9Y4C0'], 'TrEMBL':...",NaN,"[Q9HDB5, Q9Y4C0]"
5348,POLR1D,51082,17.843700,51082,"{'Swiss-Prot': ['P0DPB5', 'P0DPB6'], 'TrEMBL':...",NaN,"[P0DPB5, P0DPB6]"
5528,PRNP,5621,18.329930,5621,"{'Swiss-Prot': ['P04156', 'F7VJQ1'], 'TrEMBL':...",NaN,"[P04156, F7VJQ1]"
6178,SEM1,7979,17.231617,7979,"{'Swiss-Prot': ['Q6ZVN7', 'P60896'], 'TrEMBL':...",NaN,"[Q6ZVN7, P60896]"
6313,SIRPB1,10326,22.824057,10326,"{'Swiss-Prot': ['Q5TFQ8', 'O00241'], 'TrEMBL':...",NaN,"[Q5TFQ8, O00241]"
6742,SULT1A4,445329,27.388079,445329,"{'Swiss-Prot': ['P0DMN0', 'P0DMM9'], 'TrEMBL':...",NaN,"[P0DMN0, P0DMM9]"

In [19]:
len(results_df['query'].unique())

7400

In [20]:
multi_map_ids = results_df[results_df['uniprot_ids'].apply(lambda x: isinstance(x, list) and len(x) > 1)]['query']

In [21]:
multi_map_uniport_ids = results_df[results_df['uniprot_ids'].apply(lambda x: isinstance(x, list) and len(x) > 1)]['uniprot_ids']

In [22]:
unique_items = set(item for sublist in multi_map_uniport_ids for item in sublist)

In [23]:
len(unique_items)

46

In [24]:
ppi[ppi['string_id'].isin(unique_items)]['string_id'].tolist()

['P0DMM9', 'P0C0L4', 'P50391']

In [25]:
targets = {'P0DMM9', 'P0C0L4', 'P50391'}

results_df[
    results_df['uniprot_ids'].apply(
        lambda x: isinstance(x, list) and any(i in targets for i in x)
    )
]

,query,_id,_score,entrezgene,uniprot,notfound,uniprot_ids
761,C4B,721,19.491293,721,"{'Swiss-Prot': ['P0C0L5', 'P0C0L4'], 'TrEMBL':...",NaN,"[P0C0L5, P0C0L4]"
4365,NPY4R2,100996758,19.823011,100996758,"{'Swiss-Prot': ['P50391', 'P0DQD5']}",NaN,"[P50391, P0DQD5]"
6742,SULT1A4,445329,27.388079,445329,"{'Swiss-Prot': ['P0DMN0', 'P0DMM9'], 'TrEMBL':...",NaN,"[P0DMN0, P0DMM9]"

In [26]:
multi_map_filter_dict = {
    'SULT1A4':'P0DMM9', 
    'C4B':'P0C0L4', 
    'NPY4R2':'P50391'}

In [27]:
filter_map_df = results_df[~results_df['uniprot_ids'].apply(lambda x: isinstance(x, list) and len(x) > 1)]

In [28]:
multi_map_filter_dict.update(
    dict(zip(filter_map_df['query'], filter_map_df['uniprot_ids']))
)

In [29]:
uniport_kegg_df = df.copy()

# map gene → uniprot_ids
uniport_kegg_df['uniprot_ids'] = uniport_kegg_df.index.map(multi_map_filter_dict)

# drop rows with no mapping
uniport_kegg_df = uniport_kegg_df.dropna(subset=['uniprot_ids'])

In [30]:
uniport_kegg_df

,ABC transporters,AGE-RAGE signaling pathway in diabetic complications,AMPK signaling pathway,Acute myeloid leukemia,Adherens junction,Adipocytokine signaling pathway,Adrenergic signaling in cardiomyocytes,African trypanosomiasis,"Alanine, aspartate and glutamate metabolism",Alcoholism,...,Vitamin digestion and absorption,Wnt signaling pathway,alpha-Linolenic acid metabolism,beta-Alanine metabolism,cAMP signaling pathway,cGMP-PKG signaling pathway,mRNA surveillance pathway,mTOR signaling pathway,p53 signaling pathway,uniprot_ids
A2M,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,P01023
A3GALT2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,U3KPV4
A4GALT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Q9NPC4
AAAS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Q9NRG9
AACS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Q86V21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,A6NK75
ZNF99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,A8MXY4
ZNRF3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Q9ULT6
ZSCAN32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Q9NX65
ZYX,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Q15942

In [31]:
ppi.shape, uniport_kegg_df.shape

((17222, 129), (7377, 309))

In [33]:
len(set(set(ppi['string_id'].tolist())&set(uniport_kegg_df['uniprot_ids'].tolist())))

6728

In [34]:
set(set(uniport_kegg_df['uniprot_ids'].tolist())-set(ppi['string_id'].tolist()))

{'A0A087WWS6',
 'A0A087X1C5',
 'A0A096LP55',
 'A4GXA9',
 'A6NDH6',
 'A6NFI3',
 'A6NGB9',
 'A6NGY5',
 'A6NH00',
 'A6NHX0',
 'A6NI73',
 'A6NIX2',
 'A6NIY4',
 'A6NKK0',
 'A6NL08',
 'A6NM03',
 'A6NMZ5',
 'A6NNF4',
 'A6NNV3',
 'A8K0Z3',
 'A8MPY1',
 'A8MT65',
 'A8MUV8',
 'A8MW95',
 'A8MXY4',
 'A8TX70',
 'O00255',
 'O00303',
 'O00462',
 'O14512',
 'O14514',
 'O14581',
 'O14639',
 'O14788',
 'O14841',
 'O15041',
 'O15042',
 'O15143',
 'O15160',
 'O15197',
 'O15439',
 'O15467',
 'O15554',
 'O43323',
 'O43432',
 'O43508',
 'O43511',
 'O43677',
 'O43826',
 'O43869',
 'O60237',
 'O60404',
 'O60602',
 'O60610',
 'O60907',
 'O75015',
 'O75044',
 'O75123',
 'O75342',
 'O75396',
 'O75582',
 'O75747',
 'O75911',
 'O75970',
 'O76094',
 'O76100',
 'O95045',
 'O95049',
 'O95072',
 'O95136',
 'O95222',
 'O95342',
 'O95544',
 'O95999',
 'P00326',
 'P00338',
 'P00736',
 'P00915',
 'P01042',
 'P01229',
 'P01569',
 'P02549',
 'P02654',
 'P02671',
 'P02746',
 'P04075',
 'P05062',
 'P05106',
 'P05161',
 'P05771',
 'P06858',
 'P07108',
 'P07196',
 'P07360',
 'P07478',
 'P07510',
 'P07910',
 'P07951',
 'P08069',
 'P08397',
 'P08559',
 'P08575',
 'P08637',
 'P08686',
 'P08708',
 'P0C617',
 'P0C629',
 'P0C645',
 'P0C7N5',
 'P0C7T3',
 'P0CB33',
 'P0CB38',
 'P0CG29',
 'P0CI01',
 'P0DM35',
 'P0DMS8',
 'P0DN82',
 'P0DTA3',
 'P0DTE4',
 'P0DTE5',
 'P0DUD2',
 'P0DV79',
 'P10147',
 'P10635',
 'P11055',
 'P11511',
 'P13236',
 'P13501',
 'P13533',
 'P13637',
 'P13762',
 'P14222',
 'P14314',
 'P14649',
 'P14778',
 'P14854',
 'P15509',
 'P15514',
 'P16284',
 'P16410',
 'P16442',
 'P16471',
 'P16619',
 'P16885',
 'P17025',
 'P17097',
 'P17098',
 'P18089',
 'P19086',
 'P19367',
 'P19440',
 'P19526',
 'P20020',
 'P21583',
 'P21728',
 'P22413',
 'P22557',
 'P22897',
 'P24311',
 'P24557',
 'P24928',
 'P25063',
 'P25325',
 'P26196',
 'P26651',
 'P27544',
 'P27815',
 'P27986',
 'P28221',
 'P28223',
 'P28331',
 'P28347',
 'P28715',
 'P29597',
 'P29966',
 'P30411',
 'P30533',
 'P30711',
 'P30988',
 'P31213',
 'P31995',
 'P32004',
 'P32745',
 'P34130',
 'P34903',
 'P34925',
 'P34982',
 'P35218',
 'P35227',
 'P35237',
 'P35241',
 'P35680',
 'P36021',
 'P36551',
 'P36894',
 'P37275',
 'P38919',
 'P39656',
 'P40189',
 'P40197',
 'P40225',
 'P41439',
 'P41597',
 'P42263',
 'P42356',
 'P42677',
 'P43080',
 'P43353',
 'P43627',
 'P43631',
 'P43632',
 'P45379',
 'P46531',
 'P46779',
 'P46783',
 'P47736',
 'P47888',
 'P47893',
 'P48051',
 'P48145',
 'P48506',
 'P48637',
 'P49643',
 'P49720',
 'P49767',
 'P49789',
 'P49913',
 'P49917',
 'P50583',
 'P51530',
 'P51532',
 'P51659',
 'P52434',
 'P52799',
 'P53675',
 'P53677',
 'P54317',
 'P54750',
 'P55107',
 'P55283',
 'P55773',
 'P55774',
 'P56178',
 'P56748',
 'P58181',
 'P58182',
 'P58340',
 'P59646',
 'P60709',
 'P61254',
 'P61769',
 'P62081',
 'P62873',
 'P63010',
 'P63261',
 'P78347',
 'P78352',
 'P78356',
 'P78508',
 'P79483',
 'P82921',
 'P98088',
 'P98164',
 'P98187',
 'Q00266',
 'Q00975',
 'Q00987',
 'Q00994',
 'Q01118',
 'Q02080',
 'Q02817',
 'Q03252',
 'Q03519',
 'Q04844',
 'Q05086',
 'Q05940',
 'Q06136',
 'Q06416',
 'Q07869',
 'Q08043',
 'Q10570',
 'Q10981',
 'Q11201',
 'Q13085',
 'Q13126',
 'Q13144',
 'Q13191',
 'Q13214',
 'Q13224',
 'Q13356',
 'Q13360',
 'Q13451',
 'Q13454',
 'Q13607',
 'Q13636',
 'Q13642',
 'Q13724',
 'Q13772',
 'Q14050',
 'Q14164',
 'Q14952',
 'Q14953',
 'Q14954',
 'Q14999',
 'Q15034',
 'Q15147',
 'Q15276',
 'Q15438',
 'Q15475',
 'Q15617',
 'Q16288',
 'Q16552',
 'Q16587',
 'Q16611',
 'Q16627',
 'Q16663',
 'Q16678',
 'Q16798',
 'Q29983',
 'Q2QD12',
 'Q2TBC4',
 'Q32P51',
 'Q3SXZ3',
 'Q3ZCM7',
 'Q53H12',
 'Q567V2',
 'Q56P42',
 'Q5EG05',
 'Q5FVE4',
 'Q5JPH6',
 'Q5JQS5',
 'Q5JU85',
 'Q5JVG8',
 'Q5JXB2',
 'Q5K4L6',
 'Q5KSL6',
 'Q5MIZ7',
 'Q5T013',
 'Q5T4F4',
 'Q5TYW1',
 'Q5TZ20',
 'Q5UE93',
 'Q674R7',
 'Q68DD2',
 'Q6IEV9',
 'Q6IEZ7',
 'Q6IF00',
 'Q6IF99',
 'Q6IN85',
 'Q6IPT4',
 'Q6P461',
 'Q6PI48',
 'Q6UWP2',
 'Q6V0L0',
 'Q6ZMB0',
 'Q6ZMV8',
 'Q6ZNA1',
 'Q6ZVD8',
 'Q6ZYL4',
 'Q7L576',
 'Q7RTV2',
 'Q7Z3V5',
 'Q7Z406',
 'Q7Z443',
 'Q7Z7B1',
 'Q86XN6',
 'Q86YS3',
 'Q8IU85',
 'Q8IVT5',
 'Q8IW41',
 'Q8IXE1',
 'Q8IYB9',
 'Q8IZL2',
 'Q8N109',
 'Q8N127',
 'Q8N3E9',
 'Q8N6C8',
 'Q8N729',
 'Q8NCM8',
 'Q8NCW6',
 'Q8NEV1',
 'Q8NFN8',
 'Q8NFR9',
 'Q8NG75',
 'Q8NG77',
 'Q8NG78',
 'Q8NG94',
 'Q8NG97',
 'Q8NG99',
 'Q8NGB6',
 'Q8NGC1',
 'Q8NGC4',
 'Q8NGC6',
 'Q8NGC8',
 'Q8NGC9',
 'Q8NGD5',
 'Q8NGE2',
 'Q8NGE7',
 'Q8NGE8',
 'Q8NGE9',
 'Q8NGF1',
 'Q8NGF4',
 'Q8NGF9',
 'Q8NGG0',
 'Q8NGG2',
 'Q8NGG8',
 'Q8NGH5',
 'Q8NGH9',
 'Q8NGI2',
 'Q8NGJ0',
 'Q8NGJ3',
 'Q8NGJ5',
 'Q8NGJ6',
 'Q8NGK0',
 'Q8NGK1',
 'Q8NGK2',
 'Q8NGK4',
 'Q8NGK6',
 'Q8NGL2',
 'Q8NGL4',
 'Q8NGL6',
 'Q8NGL7',
 'Q8NGL9',
 'Q8NGN2',
 'Q8NGN3',
 'Q8NGN6',
 'Q8NGP4',
 'Q8NGP8',
 'Q8NGP9',
 'Q8NGQ1',
 'Q8NGQ3',
 'Q8NGQ6',
 'Q8NGR6',
 'Q8NGR8',
 'Q8NGS6',
 'Q8NGT9',
 'Q8NGV5',
 'Q8NGV6',
 'Q8NGW1',
 'Q8NGW6',
 'Q8NGX2',
 'Q8NGX5',
 'Q8NGX6',
 'Q8NGX8',
 'Q8NGX9',
 'Q8NGY0',
 'Q8NGY1',
 'Q8NGY5',
 'Q8NGY6',
 'Q8NGY9',
 'Q8NGZ3',
 'Q8NGZ6',
 'Q8NH01',
 'Q8NH04',
 'Q8NH05',
 'Q8NH07',
 'Q8NH21',
 'Q8NH42',
 'Q8NH48',
 'Q8NH51',
 'Q8NH53',
 'Q8NH54',
 'Q8NH55',
 'Q8NH67',
 'Q8NH73',
 'Q8NH74',
 'Q8NH81',
 'Q8NH87',
 'Q8NH92',
 'Q8NHB1',
 'Q8NHC5',
 'Q8NHC8',
 'Q8NHW4',
 'Q8NI17',
 'Q8NI36',
 'Q8TD47',
 'Q8TDX6',
 'Q8TEQ8',
 'Q8TF08',
 'Q8WU20',
 'Q8WUX1',
 'Q8WWW0',
 'Q8WZ94',
 'Q92535',
 'Q92608',
 'Q92752',
 'Q92764',
 'Q92804',
 'Q92878',
 'Q92887',
 'Q92952',
 'Q92979',
 'Q96AH8',
 'Q96BA8',
 'Q96BR1',
 'Q96D31',
 'Q96DT5',
 'Q96F07',
 'Q96FJ2',
 'Q96HA1',
 'Q96LI5',
 'Q96N38',
 'Q96NJ3',
 'Q96NT5',
 'Q96PE3',
 'Q96PP8',
 'Q96QT4',
 'Q96R27',
 'Q96R28',
 'Q96R30',
 'Q96R48',
 'Q96R72',
 'Q96RD0',
 'Q96RI9',
 'Q99558',
 'Q99572',
 'Q99611',
 'Q99624',
 'Q99677',
 'Q99697',
 'Q99933',
 'Q9BPW9',
 'Q9BRL6',
 'Q9BSG1',
 'Q9BTM9',
 'Q9BUX1',
 'Q9BXC0',
 'Q9BY07',
 'Q9BY31',
 'Q9BYB0',
 'Q9BYX4',
 'Q9BZB8',
 'Q9C0G6',
 'Q9GZK7',
 'Q9GZM3',
 'Q9GZM6',
 'Q9GZY0',
 'Q9H0P0',
 'Q9H172',
 'Q9H1A7',
 'Q9H205',
 'Q9H208',
 'Q9H222',
 'Q9H227',
 'Q9H2C8',
 'Q9H2S1',
 'Q9H344',
 'Q9H3M7',
 'Q9H3T3',
 'Q9HBE4',
 'Q9HCK8',
 'Q9NPD8',
 'Q9NPI6',
 'Q9NQ90',
 'Q9NQB0',
 'Q9NQR1',
 'Q9NR28',
 'Q9NRW7',
 'Q9NRY4',
 'Q9NSD4',
 'Q9NSE4',
 'Q9NSU2',
 'Q9NSY1',
 'Q9NUN5',
 'Q9NWZ3',
 'Q9NYB5',
 'Q9NYJ8',
 'Q9NYP7',
 'Q9NYR8',
 'Q9NZ52',
 'Q9NZB8',
 'Q9NZP0',
 'Q9NZP2',
 'Q9NZQ8',
 'Q9P013',
 'Q9P1Q5',
 'Q9P212',
 'Q9P2F8',
 'Q9P2N7',
 'Q9P2R7',
 'Q9UBF8',
 'Q9UBM8',
 'Q9UBN4',
 'Q9UBQ0',
 'Q9UDV7',
 'Q9UDY8',
 'Q9UGF6',
 'Q9UGF7',
 'Q9UGI9',
 'Q9UI47',
 'Q9UJW7',
 'Q9UK05',
 'Q9UKL0',
 'Q9UKL2',
 'Q9ULV8',
 'Q9ULZ1',
 'Q9UMD9',
 'Q9UMN6',
 'Q9UN88',
 'Q9UNN5',
 'Q9UP65',
 'Q9UPP2',
 'Q9UPS6',
 'Q9UQ16',
 'Q9UQ26',
 'Q9Y261',
 'Q9Y2H2',
 'Q9Y3D8',
 'Q9Y4D1',
 'Q9Y4G6',
 'Q9Y4L1',
 'Q9Y5P1',
 'Q9Y5S9',
 'Q9Y5Z6',
 'Q9Y624',
 'Q9Y672',
 'Q9Y6K9',
 'Q9Y6W5',
 'U3KPV4',
 'W6CW81'}

In [35]:
ppi[ppi['string_id']=='A0A087WWS6']

Empty DataFrame
Columns: [string_id, feature_1, feature_2, feature_3, feature_4, feature_5, feature_6, feature_7, feature_8, feature_9, feature_10, feature_11, feature_12, feature_13, feature_14, feature_15, feature_16, feature_17, feature_18, feature_19, feature_20, feature_21, feature_22, feature_23, feature_24, feature_25, feature_26, feature_27, feature_28, feature_29, feature_30, feature_31, feature_32, feature_33, feature_34, feature_35, feature_36, feature_37, feature_38, feature_39, feature_40, feature_41, feature_42, feature_43, feature_44, feature_45, feature_46, feature_47, feature_48, feature_49, feature_50, feature_51, feature_52, feature_53, feature_54, feature_55, feature_56, feature_57, feature_58, feature_59, feature_60, feature_61, feature_62, feature_63, feature_64, feature_65, feature_66, feature_67, feature_68, feature_69, feature_70, feature_71, feature_72, feature_73, feature_74, feature_75, feature_76, feature_77, feature_78, feature_79, feature_80, feature_81, feature_82, feature_83, feature_84, feature_85, feature_86, feature_87, feature_88, feature_89, feature_90, feature_91, feature_92, feature_93, feature_94, feature_95, feature_96, feature_97, feature_98, feature_99, ...]
Index: []

[0 rows x 129 columns]

In [36]:
with open('/itf-fi-ml/shared/users/ziyuzh/svm/data/stringdb/2023/name_convert.pkl', 'rb') as f:
    ppi_name_convert = pickle.load(f)

In [37]:
name2string = ppi_name_convert[1]

In [48]:
# name2string['IFNA13']
name2string['OR5H1']

'9606.ENSP00000492953'

In [40]:
ppi_connection = pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/stringdb/2019/9606.protein.links.v10.5.txt', sep=' ', header=0).convert_dtypes().replace(0, float('nan'))

In [41]:
ppi_connection[['protein1', 'protein2']] = np.sort(ppi_connection[['protein1', 'protein2']], axis=1)
ppi_connection = ppi_connection.drop_duplicates()

In [42]:
import networkx as nx

# Convert to NetworkX graph
G = nx.from_pandas_edgelist(ppi_connection, 'protein1', 'protein2')

In [46]:
ppi_2019_nodes = list(G.nodes)

In [49]:
# if '9606.ENSP00000480467' in ppi_2019_nodes:
if '9606.ENSP00000492953' in ppi_2019_nodes:
    print(1)

In [ ]:
# Query mygene for UniProt and Entrez gene ID mappings
temp = mg.querymany(
    [''],
    scopes='symbol',
    fields='uniprot,entrezgene',
    species='human'
)

### get ready

In [ ]:
uniport_kegg_df = uniport_kegg_df.rename(columns={'uniprot_ids': 'string_id'})
ppi

## disease labels

In [ ]:
dga = pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/disgent_2020/timecut/dga_time_uniport.csv')
time = 2019

In [ ]:
merge_dga = dga[dga['string_id'].isin(ppi['string_id'])]

selected_diseases = []
dfs = []

for disease_id in merge_dga['disease_id'].unique():
    sub_df = merge_dga[merge_dga['disease_id'] == disease_id]
    
    if len(sub_df) < 15:
        continue
    
    if (
        sub_df['first_pub_year'].max() > time and
        sub_df['first_pub_year'].min() <= time and
        len(sub_df[sub_df['first_pub_year'] < time]) >= 5
    ):
        selected_diseases.append(disease_id)
        
        # label: test = 1 if first_pub_year > time, else 0
        sub_df = sub_df.copy()
        sub_df['label'] = (sub_df['first_pub_year'] > time).astype(int)
        
        dfs.append(sub_df)

# final dataset
final_df = pd.concat(dfs, ignore_index=True)

rows = []

for d in final_df['disease_id'].unique():
    sub_df = final_df[final_df['disease_id'] == d]
    
    all_labels = len(sub_df)
    test_num = (sub_df['label'] == 1).sum()
    train_num = all_labels - test_num
    
    rows.append({
        'disease_id': d,
        'all_labels': all_labels,
        'test_num': test_num,
        'train_num': train_num
    })

summary_df = pd.DataFrame(rows)

In [64]:
merge_dga = dga[dga['string_id'].isin(uniport_kegg_df['string_id'])]

selected_diseases = []
dfs = []

for disease_id in merge_dga['disease_id'].unique():
    sub_df = merge_dga[merge_dga['disease_id'] == disease_id]
    
    if len(sub_df) < 15:
        continue
    
    if (
        sub_df['first_pub_year'].max() > time and
        sub_df['first_pub_year'].min() <= time and
        len(sub_df[sub_df['first_pub_year'] < time]) >= 5
    ):
        selected_diseases.append(disease_id)
        
        # label: test = 1 if first_pub_year > time, else 0
        sub_df = sub_df.copy()
        sub_df['label'] = (sub_df['first_pub_year'] > time).astype(int)
        
        dfs.append(sub_df)

# final dataset
final_df = pd.concat(dfs, ignore_index=True)

rows = []

for d in final_df['disease_id'].unique():
    sub_df = final_df[final_df['disease_id'] == d]
    
    all_labels = len(sub_df)
    test_num = (sub_df['label'] == 1).sum()
    train_num = all_labels - test_num
    
    rows.append({
        'disease_id': d,
        'all_labels': all_labels,
        'test_num': test_num,
        'train_num': train_num
    })

summary_df2 = pd.DataFrame(rows)

In [65]:
len(summary_df),len(summary_df2)

(48, 39)

In [66]:
summary_df['all_labels'].sum(),summary_df2['all_labels'].sum()

(5295, 3529)