In [1]:
import pandas as pd
import os

In [2]:

def rewrite_all_results(root, fused):
    top = False
    if top == True:
        num = 12
    all_results = []
    counter = 0
    if fused:
        for disease in os.listdir(root):
            if disease.startswith('ICD'):
                counter += 1
                result_df = pd.read_csv(os.path.join(root,disease))
                mean_df = result_df.groupby(['method','para'])[['top_recall_25','top_recall_300','top_recall_10%', 'top_precision_10%', 'max_precision_10%','top_recall_30%', 'top_precision_30%', 'max_precision_30%','pm_0.5%','pm_1%','pm_5%','pm_10%','pm_15%','pm_20%','pm_25%','pm_30%','auroc',"rank_ratio",'bedroc_1','bedroc_5','bedroc_10','bedroc_30']].mean().reset_index()
                # Add disease information
                mean_df['disease'] = disease.split('.')[0]
                # Append to all_results list
                all_results.append(mean_df)
            if top == True:
                if counter == num:
                    break
        # Concatenate all results into a single DataFrame
        final_result = pd.concat(all_results, ignore_index=True)
        if top == True:
            final_result.to_csv(os.path.join(root,f'all_disease_{num}.csv'),index=False)
        else:
            final_result.to_csv(os.path.join(root,'all_disease.csv'),index=False)
        return final_result
    else:
        for disease in os.listdir(root):
            if disease.startswith('ICD'):
                counter += 1
                result_df = pd.read_csv(os.path.join(root,disease))
                mean_df = result_df.groupby(['method'])[['top_recall_25','top_recall_300','top_recall_10%', 'top_precision_10%', 'max_precision_10%','top_recall_30%', 'top_precision_30%', 'max_precision_30%','pm_0.5%','pm_1%','pm_5%','pm_10%','pm_15%','pm_20%','pm_25%','pm_30%','auroc',"rank_ratio",'bedroc_1','bedroc_5','bedroc_10','bedroc_30']].mean().reset_index()
                # Add disease information
                mean_df['disease'] = disease.split('.')[0]
                # Append to all_results list
                all_results.append(mean_df)
            if top == True:
                if counter == num:
                    break
        # Concatenate all results into a single DataFrame
        final_result = pd.concat(all_results, ignore_index=True)
        if top == True:
            final_result.to_csv(os.path.join(root,f'all_disease_{num}.csv'),index=False)
        else:
            final_result.to_csv(os.path.join(root,'all_disease.csv'),index=False)
        return final_result

def create_summary(results,col_name, fused):
    # Create an empty list to store results
    summary_list = []
    if fused == False:
        # Grouping by 'method' and calculating mean and std for selected metrics
        for method, subdf in results.groupby(col_name):
            mean_values = subdf.iloc[:, 1:23].mean()  # Selecting all metric columns
            std_values = subdf.iloc[:, 1:23].std()
            summary_list.append({
                'method': method,
                'top_recall_25_mean': mean_values['top_recall_25'], 'top_recall_25_std': std_values['top_recall_25'],
                'top_recall_300_mean': mean_values['top_recall_300'], 'top_recall_300_std': std_values['top_recall_300'],
                'top_recall_10_mean': mean_values['top_recall_10%'], 'top_recall_10_std': std_values['top_recall_10%'],
                'top_precision_10_mean': mean_values['top_precision_10%'], 'top_precision_10_std': std_values['top_precision_10%'],
                'max_precision_10_mean': mean_values['max_precision_10%'], 'max_precision_10_std': std_values['max_precision_10%'],
                'top_recall_30_mean': mean_values['top_recall_30%'], 'top_recall_10_std': std_values['top_recall_30%'],
                'top_precision_30_mean': mean_values['top_precision_30%'], 'top_precision_10_std': std_values['top_precision_30%'],
                'max_precision_30_mean': mean_values['max_precision_30%'], 'max_precision_10_std': std_values['max_precision_30%'],
                'pm_0.5%': mean_values['pm_0.5%'], 'pm_0.5%_std': std_values['pm_0.5%'],
                'pm_1%': mean_values['pm_1%'], 'pm_1%_std': std_values['pm_1%'],
                'pm_5%': mean_values['pm_5%'], 'pm_5%_std': std_values['pm_5%'],
                'pm_10%': mean_values['pm_10%'], 'pm_10%_std': std_values['pm_10%'],
                'pm_15%': mean_values['pm_15%'], 'pm_15%_std': std_values['pm_15%'],            
                'pm_20%': mean_values['pm_20%'], 'pm_20%_std': std_values['pm_20%'],
                'pm_25%': mean_values['pm_25%'], 'pm_1%_std': std_values['pm_25%'],
                'pm_30%': mean_values['pm_30%'], 'pm_30%_std': std_values['pm_30%'],
                'auroc_mean': mean_values['auroc'], 'auroc_std': std_values['auroc'],
                'rank_ratio_mean': mean_values['rank_ratio'], 'rank_ratio_std': std_values['rank_ratio'],
                'bedroc_1_mean': mean_values['bedroc_1'], 'bedroc_1_std': std_values['bedroc_1'],
                'bedroc_5_mean': mean_values['bedroc_5'], 'bedroc_5_std': std_values['bedroc_5'],
                'bedroc_10_mean': mean_values['bedroc_10'], 'bedroc_10_std': std_values['bedroc_10'],
                'bedroc_30_mean': mean_values['bedroc_30'], 'bedroc_30_std': std_values['bedroc_30'],
            })

        # Convert the list of dictionaries into a DataFrame
        summary_df = pd.DataFrame(summary_list)
    else:
                # Grouping by 'method' and calculating mean and std for selected metrics
        for paras, subdf in results.groupby(col_name):
            mean_values = subdf.iloc[:, 2:24].mean()  # Selecting all metric columns
            std_values = subdf.iloc[:, 2:24].std()
            summary_list.append({
                'method': paras[0],
                'para': paras[1],
                'top_recall_25_mean': mean_values['top_recall_25'], 'top_recall_25_std': std_values['top_recall_25'],
                'top_recall_300_mean': mean_values['top_recall_300'], 'top_recall_300_std': std_values['top_recall_300'],
                'top_recall_10_mean': mean_values['top_recall_10%'], 'top_recall_10_std': std_values['top_recall_10%'],
                'top_precision_10_mean': mean_values['top_precision_10%'], 'top_precision_10_std': std_values['top_precision_10%'],
                'max_precision_10_mean': mean_values['max_precision_10%'], 'max_precision_10_std': std_values['max_precision_10%'],
                'top_recall_30_mean': mean_values['top_recall_30%'], 'top_recall_10_std': std_values['top_recall_30%'],
                'top_precision_30_mean': mean_values['top_precision_30%'], 'top_precision_10_std': std_values['top_precision_30%'],
                'max_precision_30_mean': mean_values['max_precision_30%'], 'max_precision_10_std': std_values['max_precision_30%'],
                'pm_0.5%': mean_values['pm_0.5%'], 'pm_0.5%_std': std_values['pm_0.5%'],
                'pm_1%': mean_values['pm_1%'], 'pm_1%_std': std_values['pm_1%'],
                'pm_5%': mean_values['pm_5%'], 'pm_5%_std': std_values['pm_5%'],
                'pm_10%': mean_values['pm_10%'], 'pm_10%_std': std_values['pm_10%'],
                'pm_15%': mean_values['pm_15%'], 'pm_15%_std': std_values['pm_15%'],            
                'pm_20%': mean_values['pm_20%'], 'pm_20%_std': std_values['pm_20%'],
                'pm_25%': mean_values['pm_25%'], 'pm_1%_std': std_values['pm_25%'],
                'pm_30%': mean_values['pm_30%'], 'pm_30%_std': std_values['pm_30%'],
                'auroc_mean': mean_values['auroc'], 'auroc_std': std_values['auroc'],
                'rank_ratio_mean': mean_values['rank_ratio'], 'rank_ratio_std': std_values['rank_ratio'],
                'bedroc_1_mean': mean_values['bedroc_1'], 'bedroc_1_std': std_values['bedroc_1'],
                'bedroc_5_mean': mean_values['bedroc_5'], 'bedroc_5_std': std_values['bedroc_5'],
                'bedroc_10_mean': mean_values['bedroc_10'], 'bedroc_10_std': std_values['bedroc_10'],
                'bedroc_30_mean': mean_values['bedroc_30'], 'bedroc_30_std': std_values['bedroc_30'],
            })

        # Convert the list of dictionaries into a DataFrame
        summary_df = pd.DataFrame(summary_list)
    return summary_df

In [3]:
from IPython.display import display, HTML

In [4]:
def show_table(root, fused, input_weights):
    if fused:
        final_result = rewrite_all_results(root, fused=True)
        if input_weights:
            weight_df = final_result.copy()
            weight_df[['para', 'weights']] = weight_df['para'].str.split('-', expand=True)
            all_sum = create_summary(weight_df.drop(columns='weights'), ['method', 'para'], fused=True)
            show_df = all_sum.sort_values(by='method', ascending=True) \
                .loc[:, all_sum.columns.str.contains(
                    'method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|rank_ratio', case=False)] \
                .round(3).rename(columns=lambda x: x.replace('_mean', ''))
            display(HTML(show_df.to_html(index=False).replace('<table', '<table style="font-size:13px; white-space:nowrap;"')))
            return weight_df
        else:
            all_sum = create_summary(final_result, ['method', 'para'], fused=True)
            show_df = all_sum.sort_values(by='method', ascending=True) \
                .loc[:, all_sum.columns.str.contains(
                    'method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean| rank_ratio', case=False)] \
                .round(3).rename(columns=lambda x: x.replace('_mean', ''))
            display(HTML(show_df.to_html(index=False).replace('<table', '<table style="font-size:13px; white-space:nowrap;"')))
            return final_result
    else:
        final_result = rewrite_all_results(root, fused=False)
        all_sum = create_summary(final_result, 'method', fused=False)
        if 'random_pos_negative_bagging' in all_sum['method'].unique():
            method_order = ['random_negativeauroc', 'random_negative_bagging', 'random_pos_negative_bagging']
            all_sum['method'] = pd.Categorical(all_sum['method'], categories=method_order, ordered=True)
        
        show_df = all_sum.sort_values(by='method', ascending=True) \
            .loc[:, all_sum.columns.str.contains(
                'method|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|rank_ratio', case=False)] \
            .round(3).rename(columns=lambda x: x.replace('_mean', ''))
        
        display(HTML(show_df.to_html(index=False).replace('<table', '<table style="font-size:13px; white-space:nowrap;"')))
        return final_result

    

icd_dict = {
    'Certain infectious and parasitic diseases': ['A00','B99'],
    'Neoplasms': ['C00','D48'],
    'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism': ['D50','D89'],
    'Endocrine, nutritional and metabolic diseases': ['E00','E90'],
    'Mental and behavioural disorders': ['F00','F99'],
    'Diseases of the nervous system': ['G00','G99'],
    'Diseases of the eye and adnexa': ['H00','H59'],
    'Diseases of the ear and mastoid process': ['H60','H95'],
    'Diseases of the circulatory system': ['I00','I99'],
    'Diseases of the respiratory system': ['J00','J99'],
    'Diseases of the digestive system': ['K00','K93'],
    'Diseases of the skin and subcutaneous tissue': ['L00','L99'],
    'Diseases of the musculoskeletal system and connective tissue': ['M00','M99'],
    'Diseases of the genitourinary system': ['N00','N99']
}

def find_disease_category(icd_code):
    icd_num = icd_code.split('_')[1]  # Extract ICD-10 code
    # print(icd_num)
    icd_letter = icd_num[0]  # Extract first letter (C, D, etc.)
    icd_number = int(icd_num[1:])  # Extract numeric part

    for category, (start, end) in icd_dict.items():
        start_letter, start_num = start[0], int(start[1:])
        end_letter, end_num = end[0], int(end[1:])

        if start_letter <= icd_letter <= end_letter:  # Ensure it's within the letter range
            if start_letter == icd_letter and start_num <= icd_number:
                return category
            if end_letter == icd_letter and icd_number <= end_num:
                return category
            if start_letter < icd_letter < end_letter:
                return category  # Covers ranges like C00-D48
        
    return 'Unknown Category'

def disease_catygory(results):
    mapped_results = {icd: find_disease_category(icd) for icd in results['disease']}
    results['category'] = results['disease'].map(mapped_results)

    collected_dfs = []
    disease_num = dict()
    for category in results['category'].unique().tolist():
        subdf = results[results['category'] == category].copy()
        sum_df = create_summary(subdf, 'method', fused=False)
        sum_df['category'] = category
        collected_dfs.append(sum_df)
        disease_num[category] = len(subdf) / 2

    final_df = pd.concat(collected_dfs, ignore_index=True)

    category_order = final_df.groupby('category', observed=True)['auroc_mean'].mean().sort_values(ascending=False).index.tolist()
    final_df['category'] = pd.Categorical(final_df['category'], categories=category_order, ordered=True)

    show_df = final_df.sort_values(by=['category', 'auroc_mean'], ascending=[True, False]) \
        .loc[:, final_df.columns.str.contains('method|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|category', case=False)] \
        .round(3) \
        .rename(columns=lambda x: x.replace('_mean', ''))

    # Highlight specific method
    def highlight_method(val):
        if isinstance(val, str) and val == 'random_pos_negative_bagging':
            return '<span style="color:red; font-weight:bold;">random_pos_negative_bagging</span>'
        return val

    styled_df = show_df.copy()
    if 'method' in styled_df.columns:
        styled_df['method'] = styled_df['method'].apply(highlight_method)

    # Assign background colors per category
    category_colors = {}
    base_colors = ['#ffdddd', "#dbf7db"]
    for i, cat in enumerate(category_order):
        category_colors[cat] = base_colors[i % len(base_colors)]

    def row_style(row):
        color = category_colors.get(row['category'], '#ffffff')
        return [f'background-color: {color}'] * len(row)


    # Display styled table
    from IPython.display import display, HTML
    display(HTML(styled_df.style.apply(row_style, axis=1).to_html(escape=False)))


# def disease_catygory_fused(results):
#     mapped_results = {icd: find_disease_category(icd) for icd in results['disease']}
#     results['category'] = results['disease'].map(mapped_results)

#     collected_dfs = []
#     disease_num = dict()
#     for category in results['category'].unique().tolist():
#         subdf = results[results['category'] == category].copy()
#         subdf = subdf.drop(columns='weights')
#         sum_df = create_summary(subdf, ['method', 'para'], fused=True)
#         sum_df['category'] = category
#         collected_dfs.append(sum_df)
#         disease_num[category] = len(subdf) / 2

#     final_df = pd.concat(collected_dfs, ignore_index=True)

#     category_order = final_df.groupby('category', observed=True)['auroc_mean'].mean().sort_values(ascending=False).index.tolist()
#     final_df['category'] = pd.Categorical(final_df['category'], categories=category_order, ordered=True)

#     show_df = final_df.sort_values(by=['category', 'auroc_mean'], ascending=[True, False]) \
#         .loc[:, final_df.columns.str.contains('method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|category', case=False)] \
#         .round(3) \
#         .rename(columns=lambda x: x.replace('_mean', ''))

#     # Define the custom order for 'feature'
#     feature_order = ['ppi_2019', 'bioconcept', 'esm2', 'uniport', 
#                     'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

#     # Convert 'feature' to a categorical type with that order
#     show_df['para'] = pd.Categorical(show_df['para'], categories=feature_order, ordered=True)

#     # Now sort by 'disease' first, then 'feature' by the custom order
#     show_df = show_df.sort_values(by=['category', 'para'])
    
#     # Define alternating background colors per disease
#     base_colors = ['#ffdddd', '#dbf7db']
#     target_cols = ['auroc', 'bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30', 'weights']

#     # Build mapping for background colors per disease
#     diseases = show_df['disease'].unique()
#     disease_color_map = {disease: base_colors[i % len(base_colors)] for i, disease in enumerate(diseases)}

#     # Function to create full styling DataFrame
#     def combined_style(df):
#         styles = pd.DataFrame('', index=df.index, columns=df.columns)

#         # Add background color row-wise
#         for idx, row in df.iterrows():
#             bg_color = disease_color_map[row['disease']]
#             styles.loc[idx, :] = f'background-color: {bg_color};'

#         # Highlight max in each group & each target column
#         for disease, group in df.groupby('disease'):
#             for col in target_cols:
#                 max_val = group[col].max()
#                 max_indices = group[group[col] == max_val].index
#                 for idx in max_indices:
#                     styles.loc[idx, col] += ' color: red; font-weight: bold;'
        
#         return styles

#     # Apply combined style
#     styled_df = show_df.style.apply(combined_style, axis=None)
#     return styled_df

In [7]:
root = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2017_cv'
# root = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_fused_geo_weight_bag_new_kernel_uni'

fused_2019 = show_table(root,fused = True, input_weights = True)

In [8]:
full_fused_2019 = fused_2019
mapped_results = {icd: find_disease_category(icd) for icd in full_fused_2019['disease']}
full_fused_2019['category'] = full_fused_2019['disease'].map(mapped_results)

In [9]:
full_fused_2019

,method,para,top_recall_25,top_recall_300,top_recall_10%,top_precision_10%,max_precision_10%,top_recall_30%,top_precision_30%,max_precision_30%,...,pm_30%,auroc,rank_ratio,bedroc_1,bedroc_5,bedroc_10,bedroc_30,disease,weights,category
0,random_negative,geo_fused,0.000000,0.000000,1.000000,0.000657,0.000657,1.000000,0.000219,0.000219,...,0.769277,0.975434,0.0246,1.920689e-02,4.533964e-01,6.733471e-01,0.877313,ICD10_E10,0.269,"Endocrine, nutritional and metabolic diseases"
1,random_negative,linear_fused,0.000000,1.000000,1.000000,0.000657,0.000657,1.000000,0.000219,0.000219,...,0.769277,0.992578,0.0075,3.029461e-01,7.874239e-01,8.873691e-01,0.961233,ICD10_E10,0.267,"Endocrine, nutritional and metabolic diseases"
2,random_negative,uniport_esm,0.000000,0.000000,0.000000,0.000000,0.000657,0.000000,0.000000,0.000219,...,0.000000,0.141750,0.8583,1.074365e-60,9.867955e-13,8.966583e-07,0.005619,ICD10_E10,0.215,"Endocrine, nutritional and metabolic diseases"
3,random_negative,uniport_exp,0.000000,0.000000,1.000000,0.000657,0.000657,1.000000,0.000219,0.000219,...,0.769277,0.937007,0.0631,3.967257e-05,1.315682e-01,3.627233e-01,0.714745,ICD10_E10,0.176,"Endocrine, nutritional and metabolic diseases"
4,random_negative,uniport_ppi_2017,1.000000,1.000000,1.000000,0.000657,0.000657,1.000000,0.000219,0.000219,...,0.769277,0.999606,0.0005,9.385596e-01,9.873905e-01,9.936753e-01,0.997903,ICD10_E10,0.273,"Endocrine, nutritional and metabolic diseases"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,random_negative,uniport_exp,0.000000,0.111111,0.407407,0.007251,0.017798,0.666667,0.003955,0.005933,...,0.690150,0.803238,0.1973,6.363380e-02,1.420246e-01,2.252931e-01,0.453638,ICD10_C67,0.023,Neoplasms
404,random_negative,uniport_ppi_2017,0.148148,0.481481,0.666667,0.011866,0.017798,0.740741,0.004395,0.005933,...,0.712309,0.813196,0.1874,2.827804e-01,4.773147e-01,5.571157e-01,0.668110,ICD10_C67,0.282,Neoplasms
405,random_negative,uniport_seq,0.000000,0.296296,0.333333,0.005933,0.017798,0.518519,0.003076,0.005933,...,0.633817,0.770584,0.2303,6.382837e-02,2.179705e-01,2.772654e-01,0.435037,ICD10_C67,0.174,Neoplasms
406,random_negative,weighted_geo_fused,0.259259,0.518519,0.666667,0.011866,0.017798,0.740741,0.004395,0.005933,...,0.712309,0.825145,0.1755,3.814821e-01,5.135790e-01,5.777479e-01,0.679464,ICD10_C67,0.255,Neoplasms
407,random_negative,weighted_linear_fused,0.074074,0.481481,0.703704,0.012525,0.017798,0.740741,0.004395,0.005933,...,0.712309,0.815930,0.1847,2.855724e-01,4.714709e-01,5.558563e-01,0.672634,ICD10_C67,0.297,Neoplasms

In [ ]:
# full_fused_2019.to_csv('/itf-fi-ml/shared/users/ziyuzh/svm/results/single_weighted_fused_2019_bag.csv',index=False)

In [ ]:
# full_fused_2019=pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/results/single_weighted_fused_2019_bag.csv')

In [10]:
# full_fused_2019 = pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/results/weighted_fused_2019.csv')
full_fused_2019 = full_fused_2019[['method', 'para', 'auroc','bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30', 'weights','disease', 'category']]

In [11]:
full_fused_2019['para'].unique()

array(['geo_fused', 'linear_fused', 'uniport_esm', 'uniport_exp',
       'uniport_ppi_2017', 'uniport_seq', 'weighted_geo_fused',
       'weighted_linear_fused'], dtype=object)

In [12]:
# full_fused_2019['weights'] = full_fused_2019['weights'].astype(float)
full_fused_2019 = full_fused_2019.round(3)
# full_fused_2019 = full_fused_2019.rename(columns={'para': 'feature'})
# feature_order = ['DL']
 

feature_order = ['uniport_ppi_2017', 'uniport_bio', 'uniport_esm', 'uniport_seq', 
                 'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# feature_order = ['uniport_ppi_2019', 'uniport_bio', 'uniport_esm', 'uniport_seq', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# # Define the custom order for 'feature'
# feature_order = ['ppi_2019', 'bioconcept', 'esm2', 'uniport', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# feature_order = ['ppi_2017', 'gene2vec', 'esm2', 'uniport', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# Convert 'feature' to a categorical type with that order
full_fused_2019['para'] = pd.Categorical(full_fused_2019['para'], categories=feature_order, ordered=True)

# Now sort by 'disease' first, then 'feature' by the custom order
full_fused_2019 = full_fused_2019.sort_values(by=['disease', 'para'])

In [13]:
target_cols = ['auroc', 'bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30']

# Define alternating background colors per disease
base_colors = ['#ffdddd', '#dbf7db']
diseases = full_fused_2019['disease'].unique()
disease_color_map = {disease: base_colors[i % len(base_colors)] for i, disease in enumerate(diseases)}

def combined_style(df):
    styles = pd.DataFrame('', index=df.index, columns=df.columns)

    # Add background color row-wise
    for idx, row in df.iterrows():
        bg_color = disease_color_map[row['disease']]
        styles.loc[idx, :] = f'background-color: {bg_color};'

    # Highlight max in each group & each target column
    for category, group in df.groupby('disease'):
        for col in target_cols:
            max_val = group[col].max()
            max_indices = group[group[col] == max_val].index
            for idx in max_indices:
                styles.loc[idx, col] += ' color: red; font-weight: bold;'
    
    return styles

In [14]:
# Build mapping for background colors per disease
# full_fused_2019['para'] = full_fused_2019['para'].str.replace('ppi_2016', 'ppi_2017', regex=False)
full_fused_2019_disease = full_fused_2019.style.apply(combined_style, axis=None)


full_fused_2019_disease

In [ ]:
# abnormal = ['ICD10_C43','ICD10_N80','ICD10_N18', 'ICD10_G24', 'ICD10_E66', 'ICD10_D83', 'ICD10_C50']
# results = fused_2019[~fused_2019['disease'].isin(abnormal)]
# fused_2019

In [15]:
# fused_2019['para'] = fused_2019['para'].str.replace('ppi_2016', 'ppi_2017', regex=False)
results = fused_2019
mapped_results = {icd: find_disease_category(icd) for icd in results['disease']}
results['category'] = results['disease'].map(mapped_results)

collected_dfs = []
disease_num = dict()
for category in results['category'].unique().tolist():
    subdf = results[results['category'] == category].copy()
    subdf = subdf.drop(columns='weights')
    sum_df = create_summary(subdf, ['method', 'para'], fused=True)
    sum_df['category'] = category
    collected_dfs.append(sum_df)
    disease_num[category] = len(subdf) / 2

final_df = pd.concat(collected_dfs, ignore_index=True)

category_order = final_df.groupby('category', observed=True)['auroc_mean'].mean().sort_values(ascending=False).index.tolist()
final_df['category'] = pd.Categorical(final_df['category'], categories=category_order, ordered=True)

show_df = final_df.sort_values(by=['category', 'auroc_mean'], ascending=[True, False]) \
    .loc[:, final_df.columns.str.contains('method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|category', case=False)] \
    .round(3) \
    .rename(columns=lambda x: x.replace('_mean', ''))

# feature_order = ['ppi_2017', 'gene2vec', 'esm2', 'uniport', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# Convert 'feature' to a categorical type with that order
show_df['para'] = pd.Categorical(show_df['para'], categories=feature_order, ordered=True)

# Now sort by 'disease' first, then 'feature' by the custom order
show_df = show_df.sort_values(by=['category', 'para'])

# Define alternating background colors per disease
base_colors = ['#ffdddd', '#dbf7db']


# Build mapping for background colors per disease
category = show_df['category'].unique()
color_map = {disease: base_colors[i % len(base_colors)] for i, disease in enumerate(category)}

In [16]:
target_cols = ['auroc', 'bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30']

def combined_style2(df):
    styles = pd.DataFrame('', index=df.index, columns=df.columns)

    # Add background color row-wise
    for idx, row in df.iterrows():
        bg_color = color_map[row['category']]
        styles.loc[idx, :] = f'background-color: {bg_color};'

    # Highlight max in each group & each target column
    for category, group in df.groupby('category'):
        for col in target_cols:
            max_val = group[col].max()
            max_indices = group[group[col] == max_val].index
            for idx in max_indices:
                styles.loc[idx, col] += ' color: red; font-weight: bold;'
    
    return styles

# Apply combined style
styled_df = show_df.style.apply(combined_style2, axis=None)
styled_df
# styled_df.to_excel("/itf-fi-ml/shared/users/ziyuzh/svm/results/styled_2019_fused_weighted.xlsx", engine="openpyxl", index = False)

/tmp/ipykernel_3948199/1906553618.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for category, group in df.groupby('category'):

In [ ]:
# with pd.ExcelWriter('/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_fused.xlsx', engine='openpyxl') as writer:
#     styled_df.to_excel(writer, sheet_name='category', index=False)
#     full_fused_2019_disease.to_excel(writer, sheet_name='disease', index=False)

/tmp/ipykernel_3370025/1906553618.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for category, group in df.groupby('category'):

In [ ]:
### choose gamma
### entire dataset, get kernel (dist matrix)
### calculate nearest dist sum
### 2 * sum = gamma

In [ ]:
######## weighted kernel, weights comes from the biology pathway overlap
# 1. train / val split (no-time-cut) cross validation??
# 2. set threshold -200
# 3. pathway enrichment of predicted FPs and TPs
# 4. enriched reults similarity (jaccard-sim, Semantics similarity between terms)
# bootstrap bioconcept, gene2vec, uniport, esm2
##### fused only ppi and bioconcept
##### fused * bootstrap_bagging
##### fused 2017

In [ ]:
### hard negative
### low scores in disgenet
### perturb positive to be neg
### simialr disease positive to be positives