In [1]:
import pandas as pd
import os

In [2]:

def rewrite_all_results(root, fused):
    top = False
    if top == True:
        num = 12
    all_results = []
    counter = 0
    if fused:
        for disease in os.listdir(root):
            if disease.startswith('ICD'):
                counter += 1
                result_df = pd.read_csv(os.path.join(root,disease))
                mean_df = result_df.groupby(['method','para'])[['top_recall_25','top_recall_300','top_recall_10%', 'top_precision_10%', 'max_precision_10%','top_recall_30%', 'top_precision_30%', 'max_precision_30%','pm_0.5%','pm_1%','pm_5%','pm_10%','pm_15%','pm_20%','pm_25%','pm_30%','auroc',"rank_ratio",'bedroc_1','bedroc_5','bedroc_10','bedroc_30']].mean().reset_index()
                # Add disease information
                mean_df['disease'] = disease.split('.')[0]
                # Append to all_results list
                all_results.append(mean_df)
            if top == True:
                if counter == num:
                    break
        # Concatenate all results into a single DataFrame
        final_result = pd.concat(all_results, ignore_index=True)
        if top == True:
            final_result.to_csv(os.path.join(root,f'all_disease_{num}.csv'),index=False)
        else:
            final_result.to_csv(os.path.join(root,'all_disease.csv'),index=False)
        return final_result
    else:
        for disease in os.listdir(root):
            if disease.startswith('ICD'):
                counter += 1
                result_df = pd.read_csv(os.path.join(root,disease))
                mean_df = result_df.groupby(['method'])[['top_recall_25','top_recall_300','top_recall_10%', 'top_precision_10%', 'max_precision_10%','top_recall_30%', 'top_precision_30%', 'max_precision_30%','pm_0.5%','pm_1%','pm_5%','pm_10%','pm_15%','pm_20%','pm_25%','pm_30%','auroc',"rank_ratio",'bedroc_1','bedroc_5','bedroc_10','bedroc_30']].mean().reset_index()
                # Add disease information
                mean_df['disease'] = disease.split('.')[0]
                # Append to all_results list
                all_results.append(mean_df)
            if top == True:
                if counter == num:
                    break
        # Concatenate all results into a single DataFrame
        final_result = pd.concat(all_results, ignore_index=True)
        if top == True:
            final_result.to_csv(os.path.join(root,f'all_disease_{num}.csv'),index=False)
        else:
            final_result.to_csv(os.path.join(root,'all_disease.csv'),index=False)
        return final_result

def create_summary(results,col_name, fused):
    # Create an empty list to store results
    summary_list = []
    if fused == False:
        # Grouping by 'method' and calculating mean and std for selected metrics
        for method, subdf in results.groupby(col_name):
            mean_values = subdf.iloc[:, 1:23].mean()  # Selecting all metric columns
            std_values = subdf.iloc[:, 1:23].std()
            summary_list.append({
                'method': method,
                'top_recall_25_mean': mean_values['top_recall_25'], 'top_recall_25_std': std_values['top_recall_25'],
                'top_recall_300_mean': mean_values['top_recall_300'], 'top_recall_300_std': std_values['top_recall_300'],
                'top_recall_10_mean': mean_values['top_recall_10%'], 'top_recall_10_std': std_values['top_recall_10%'],
                'top_precision_10_mean': mean_values['top_precision_10%'], 'top_precision_10_std': std_values['top_precision_10%'],
                'max_precision_10_mean': mean_values['max_precision_10%'], 'max_precision_10_std': std_values['max_precision_10%'],
                'top_recall_30_mean': mean_values['top_recall_30%'], 'top_recall_10_std': std_values['top_recall_30%'],
                'top_precision_30_mean': mean_values['top_precision_30%'], 'top_precision_10_std': std_values['top_precision_30%'],
                'max_precision_30_mean': mean_values['max_precision_30%'], 'max_precision_10_std': std_values['max_precision_30%'],
                'pm_0.5%': mean_values['pm_0.5%'], 'pm_0.5%_std': std_values['pm_0.5%'],
                'pm_1%': mean_values['pm_1%'], 'pm_1%_std': std_values['pm_1%'],
                'pm_5%': mean_values['pm_5%'], 'pm_5%_std': std_values['pm_5%'],
                'pm_10%': mean_values['pm_10%'], 'pm_10%_std': std_values['pm_10%'],
                'pm_15%': mean_values['pm_15%'], 'pm_15%_std': std_values['pm_15%'],            
                'pm_20%': mean_values['pm_20%'], 'pm_20%_std': std_values['pm_20%'],
                'pm_25%': mean_values['pm_25%'], 'pm_1%_std': std_values['pm_25%'],
                'pm_30%': mean_values['pm_30%'], 'pm_30%_std': std_values['pm_30%'],
                'auroc_mean': mean_values['auroc'], 'auroc_std': std_values['auroc'],
                'rank_ratio_mean': mean_values['rank_ratio'], 'rank_ratio_std': std_values['rank_ratio'],
                'bedroc_1_mean': mean_values['bedroc_1'], 'bedroc_1_std': std_values['bedroc_1'],
                'bedroc_5_mean': mean_values['bedroc_5'], 'bedroc_5_std': std_values['bedroc_5'],
                'bedroc_10_mean': mean_values['bedroc_10'], 'bedroc_10_std': std_values['bedroc_10'],
                'bedroc_30_mean': mean_values['bedroc_30'], 'bedroc_30_std': std_values['bedroc_30'],
            })

        # Convert the list of dictionaries into a DataFrame
        summary_df = pd.DataFrame(summary_list)
    else:
                # Grouping by 'method' and calculating mean and std for selected metrics
        for paras, subdf in results.groupby(col_name):
            mean_values = subdf.iloc[:, 2:24].mean()  # Selecting all metric columns
            std_values = subdf.iloc[:, 2:24].std()
            summary_list.append({
                'method': paras[0],
                'para': paras[1],
                'top_recall_25_mean': mean_values['top_recall_25'], 'top_recall_25_std': std_values['top_recall_25'],
                'top_recall_300_mean': mean_values['top_recall_300'], 'top_recall_300_std': std_values['top_recall_300'],
                'top_recall_10_mean': mean_values['top_recall_10%'], 'top_recall_10_std': std_values['top_recall_10%'],
                'top_precision_10_mean': mean_values['top_precision_10%'], 'top_precision_10_std': std_values['top_precision_10%'],
                'max_precision_10_mean': mean_values['max_precision_10%'], 'max_precision_10_std': std_values['max_precision_10%'],
                'top_recall_30_mean': mean_values['top_recall_30%'], 'top_recall_10_std': std_values['top_recall_30%'],
                'top_precision_30_mean': mean_values['top_precision_30%'], 'top_precision_10_std': std_values['top_precision_30%'],
                'max_precision_30_mean': mean_values['max_precision_30%'], 'max_precision_10_std': std_values['max_precision_30%'],
                'pm_0.5%': mean_values['pm_0.5%'], 'pm_0.5%_std': std_values['pm_0.5%'],
                'pm_1%': mean_values['pm_1%'], 'pm_1%_std': std_values['pm_1%'],
                'pm_5%': mean_values['pm_5%'], 'pm_5%_std': std_values['pm_5%'],
                'pm_10%': mean_values['pm_10%'], 'pm_10%_std': std_values['pm_10%'],
                'pm_15%': mean_values['pm_15%'], 'pm_15%_std': std_values['pm_15%'],            
                'pm_20%': mean_values['pm_20%'], 'pm_20%_std': std_values['pm_20%'],
                'pm_25%': mean_values['pm_25%'], 'pm_1%_std': std_values['pm_25%'],
                'pm_30%': mean_values['pm_30%'], 'pm_30%_std': std_values['pm_30%'],
                'auroc_mean': mean_values['auroc'], 'auroc_std': std_values['auroc'],
                'rank_ratio_mean': mean_values['rank_ratio'], 'rank_ratio_std': std_values['rank_ratio'],
                'bedroc_1_mean': mean_values['bedroc_1'], 'bedroc_1_std': std_values['bedroc_1'],
                'bedroc_5_mean': mean_values['bedroc_5'], 'bedroc_5_std': std_values['bedroc_5'],
                'bedroc_10_mean': mean_values['bedroc_10'], 'bedroc_10_std': std_values['bedroc_10'],
                'bedroc_30_mean': mean_values['bedroc_30'], 'bedroc_30_std': std_values['bedroc_30'],
            })

        # Convert the list of dictionaries into a DataFrame
        summary_df = pd.DataFrame(summary_list)
    return summary_df

In [3]:
from IPython.display import display, HTML

In [7]:
def show_table(root, fused, input_weights):
    if fused:
        final_result = rewrite_all_results(root, fused=True)
        if input_weights:
            weight_df = final_result.copy()
            weight_df[['para', 'weights']] = weight_df['para'].str.split('-', expand=True)
            all_sum = create_summary(weight_df.drop(columns='weights'), ['method', 'para'], fused=True)
            show_df = all_sum.sort_values(by='method', ascending=True) \
                .loc[:, all_sum.columns.str.contains(
                    'method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|rank_ratio', case=False)] \
                .round(3).rename(columns=lambda x: x.replace('_mean', ''))
            display(HTML(show_df.to_html(index=False).replace('<table', '<table style="font-size:13px; white-space:nowrap;"')))
            return weight_df
        else:
            all_sum = create_summary(final_result, ['method', 'para'], fused=True)
            show_df = all_sum.sort_values(by='method', ascending=True) \
                .loc[:, all_sum.columns.str.contains(
                    'method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean| rank_ratio', case=False)] \
                .round(3).rename(columns=lambda x: x.replace('_mean', ''))
            display(HTML(show_df.to_html(index=False).replace('<table', '<table style="font-size:13px; white-space:nowrap;"')))
            return final_result
    else:
        final_result = rewrite_all_results(root, fused=False)
        all_sum = create_summary(final_result, 'method', fused=False)
        if 'random_pos_negative_bagging' in all_sum['method'].unique():
            method_order = ['random_negativeauroc', 'random_negative_bagging', 'random_pos_negative_bagging']
            all_sum['method'] = pd.Categorical(all_sum['method'], categories=method_order, ordered=True)
        
        show_df = all_sum.sort_values(by='method', ascending=True) \
            .loc[:, all_sum.columns.str.contains(
                'method|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|rank_ratio', case=False)] \
            .round(3).rename(columns=lambda x: x.replace('_mean', ''))
        
        display(HTML(show_df.to_html(index=False).replace('<table', '<table style="font-size:13px; white-space:nowrap;"')))
        return final_result

    

icd_dict = {
    'Certain infectious and parasitic diseases': ['A00','B99'],
    'Neoplasms': ['C00','D48'],
    'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism': ['D50','D89'],
    'Endocrine, nutritional and metabolic diseases': ['E00','E90'],
    'Mental and behavioural disorders': ['F00','F99'],
    'Diseases of the nervous system': ['G00','G99'],
    'Diseases of the eye and adnexa': ['H00','H59'],
    'Diseases of the ear and mastoid process': ['H60','H95'],
    'Diseases of the circulatory system': ['I00','I99'],
    'Diseases of the respiratory system': ['J00','J99'],
    'Diseases of the digestive system': ['K00','K93'],
    'Diseases of the skin and subcutaneous tissue': ['L00','L99'],
    'Diseases of the musculoskeletal system and connective tissue': ['M00','M99'],
    'Diseases of the genitourinary system': ['N00','N99']
}

def find_disease_category(icd_code):
    icd_num = icd_code.split('_')[1]  # Extract ICD-10 code
    # print(icd_num)
    icd_letter = icd_num[0]  # Extract first letter (C, D, etc.)
    icd_number = int(icd_num[1:])  # Extract numeric part

    for category, (start, end) in icd_dict.items():
        start_letter, start_num = start[0], int(start[1:])
        end_letter, end_num = end[0], int(end[1:])

        if start_letter <= icd_letter <= end_letter:  # Ensure it's within the letter range
            if start_letter == icd_letter and start_num <= icd_number:
                return category
            if end_letter == icd_letter and icd_number <= end_num:
                return category
            if start_letter < icd_letter < end_letter:
                return category  # Covers ranges like C00-D48
        
    return 'Unknown Category'

def disease_catygory(results):
    mapped_results = {icd: find_disease_category(icd) for icd in results['disease']}
    results['category'] = results['disease'].map(mapped_results)

    collected_dfs = []
    disease_num = dict()
    for category in results['category'].unique().tolist():
        subdf = results[results['category'] == category].copy()
        sum_df = create_summary(subdf, 'method', fused=False)
        sum_df['category'] = category
        collected_dfs.append(sum_df)
        disease_num[category] = len(subdf) / 2

    final_df = pd.concat(collected_dfs, ignore_index=True)

    category_order = final_df.groupby('category', observed=True)['auroc_mean'].mean().sort_values(ascending=False).index.tolist()
    final_df['category'] = pd.Categorical(final_df['category'], categories=category_order, ordered=True)

    show_df = final_df.sort_values(by=['category', 'auroc_mean'], ascending=[True, False]) \
        .loc[:, final_df.columns.str.contains('method|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|category', case=False)] \
        .round(3) \
        .rename(columns=lambda x: x.replace('_mean', ''))

    # Highlight specific method
    def highlight_method(val):
        if isinstance(val, str) and val == 'random_pos_negative_bagging':
            return '<span style="color:red; font-weight:bold;">random_pos_negative_bagging</span>'
        return val

    styled_df = show_df.copy()
    if 'method' in styled_df.columns:
        styled_df['method'] = styled_df['method'].apply(highlight_method)

    # Assign background colors per category
    category_colors = {}
    base_colors = ['#ffdddd', "#dbf7db"]
    for i, cat in enumerate(category_order):
        category_colors[cat] = base_colors[i % len(base_colors)]

    def row_style(row):
        color = category_colors.get(row['category'], '#ffffff')
        return [f'background-color: {color}'] * len(row)


    # Display styled table
    from IPython.display import display, HTML
    display(HTML(styled_df.style.apply(row_style, axis=1).to_html(escape=False)))


# def disease_catygory_fused(results):
#     mapped_results = {icd: find_disease_category(icd) for icd in results['disease']}
#     results['category'] = results['disease'].map(mapped_results)

#     collected_dfs = []
#     disease_num = dict()
#     for category in results['category'].unique().tolist():
#         subdf = results[results['category'] == category].copy()
#         subdf = subdf.drop(columns='weights')
#         sum_df = create_summary(subdf, ['method', 'para'], fused=True)
#         sum_df['category'] = category
#         collected_dfs.append(sum_df)
#         disease_num[category] = len(subdf) / 2

#     final_df = pd.concat(collected_dfs, ignore_index=True)

#     category_order = final_df.groupby('category', observed=True)['auroc_mean'].mean().sort_values(ascending=False).index.tolist()
#     final_df['category'] = pd.Categorical(final_df['category'], categories=category_order, ordered=True)

#     show_df = final_df.sort_values(by=['category', 'auroc_mean'], ascending=[True, False]) \
#         .loc[:, final_df.columns.str.contains('method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|category', case=False)] \
#         .round(3) \
#         .rename(columns=lambda x: x.replace('_mean', ''))

#     # Define the custom order for 'feature'
#     feature_order = ['ppi_2019', 'bioconcept', 'esm2', 'uniport', 
#                     'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

#     # Convert 'feature' to a categorical type with that order
#     show_df['para'] = pd.Categorical(show_df['para'], categories=feature_order, ordered=True)

#     # Now sort by 'disease' first, then 'feature' by the custom order
#     show_df = show_df.sort_values(by=['category', 'para'])
    
#     # Define alternating background colors per disease
#     base_colors = ['#ffdddd', '#dbf7db']
#     target_cols = ['auroc', 'bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30', 'weights']

#     # Build mapping for background colors per disease
#     diseases = show_df['disease'].unique()
#     disease_color_map = {disease: base_colors[i % len(base_colors)] for i, disease in enumerate(diseases)}

#     # Function to create full styling DataFrame
#     def combined_style(df):
#         styles = pd.DataFrame('', index=df.index, columns=df.columns)

#         # Add background color row-wise
#         for idx, row in df.iterrows():
#             bg_color = disease_color_map[row['disease']]
#             styles.loc[idx, :] = f'background-color: {bg_color};'

#         # Highlight max in each group & each target column
#         for disease, group in df.groupby('disease'):
#             for col in target_cols:
#                 max_val = group[col].max()
#                 max_indices = group[group[col] == max_val].index
#                 for idx in max_indices:
#                     styles.loc[idx, col] += ' color: red; font-weight: bold;'
        
#         return styles

#     # Apply combined style
#     styled_df = show_df.style.apply(combined_style, axis=None)
#     return styled_df

In [9]:
root = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_fused_geo_weight_bag_new_kernel_uni_nn'
# root = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_fused_geo_weight_bag_new_kernel_uni'

fused_2019 = show_table(root,fused = True, input_weights = True)

In [6]:
fused_2019

,method,para,top_recall_25,top_recall_300,top_recall_10%,top_precision_10%,max_precision_10%,top_recall_30%,top_precision_30%,max_precision_30%,...,pm_25%,pm_30%,auroc,rank_ratio,bedroc_1,bedroc_5,bedroc_10,bedroc_30,disease,weights
0,random_negative,geo_fused,1.000000,1.000000,1.000000,0.000638,0.000638,1.000000,0.000213,0.000213,...,0.800031,0.769280,0.999170,0.0009,8.750561e-01,0.973644,0.986734,0.995591,ICD10_D66,0.104
1,random_negative,linear_fused,1.000000,1.000000,1.000000,0.000638,0.000638,1.000000,0.000213,0.000213,...,0.800031,0.769280,0.999681,0.0004,9.499617e-01,0.989779,0.994877,0.998302,ICD10_D66,0.095
2,random_negative,uniport_bio,0.000000,0.000000,0.000000,0.000000,0.000638,0.000000,0.000000,0.000213,...,0.000000,0.000000,0.661540,0.3385,2.242007e-24,0.000019,0.004301,0.162156,ICD10_D66,0.115
3,random_negative,uniport_esm,1.000000,1.000000,1.000000,0.000638,0.000638,1.000000,0.000213,0.000213,...,0.800031,0.769280,0.999681,0.0004,9.499617e-01,0.989779,0.994877,0.998302,ICD10_D66,0.157
4,random_negative,uniport_ppi_2019,1.000000,1.000000,1.000000,0.000638,0.000638,1.000000,0.000213,0.000213,...,0.800031,0.769280,0.998915,0.0011,8.398481e-01,0.965674,0.982687,0.994239,ICD10_D66,0.081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,random_negative,uniport_esm,0.000000,0.105263,0.263158,0.003224,0.012250,0.578947,0.002364,0.004083,...,0.654823,0.658949,0.684706,0.3156,3.744322e-02,0.138811,0.197949,0.368049,ICD10_C67,0.232
380,random_negative,uniport_ppi_2019,0.157895,0.421053,0.684211,0.008382,0.012250,0.684211,0.002793,0.004083,...,0.732837,0.695529,0.734892,0.2654,3.120668e-01,0.495617,0.568964,0.643843,ICD10_C67,0.266
381,random_negative,uniport_seq,0.000000,0.157895,0.421053,0.005158,0.012250,0.736842,0.003008,0.004083,...,0.747143,0.711036,0.778513,0.2219,4.847736e-02,0.167855,0.272398,0.495476,ICD10_C67,0.118
382,random_negative,weighted_geo_fused,0.105263,0.473684,0.684211,0.008382,0.012250,0.684211,0.002793,0.004083,...,0.732837,0.695529,0.782344,0.2180,2.572679e-01,0.473598,0.552954,0.646223,ICD10_C67,0.316
383,random_negative,weighted_linear_fused,0.157895,0.473684,0.684211,0.008382,0.012250,0.684211,0.002793,0.004083,...,0.732837,0.695529,0.767005,0.2334,3.208979e-01,0.497263,0.569118,0.652406,ICD10_C67,0.29

In [19]:
root = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2017_fused_geo_weight_bag_new_kernel_uni_nn_update'
fused_2019 = show_table(root,fused = True, input_weights = True)

In [21]:
full_fused_2019 = fused_2019
mapped_results = {icd: find_disease_category(icd) for icd in full_fused_2019['disease']}
full_fused_2019['category'] = full_fused_2019['disease'].map(mapped_results)

In [22]:
full_fused_2019

,method,para,top_recall_25,top_recall_300,top_recall_10%,top_precision_10%,max_precision_10%,top_recall_30%,top_precision_30%,max_precision_30%,...,pm_30%,auroc,rank_ratio,bedroc_1,bedroc_5,bedroc_10,bedroc_30,disease,weights,category
0,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000638,0.000000,0.000000,0.000213,...,0.000000,0.398315,0.6017,9.081848e-43,3.858405e-09,0.000062,0.036413,ICD10_D66,0.105,Diseases of the blood and blood-forming organs...
1,random_negative,DL,0.000000,0.040000,0.080000,0.001280,0.016005,0.400000,0.002134,0.005335,...,0.571575,0.489585,0.5104,1.024412e-02,3.638236e-02,0.058757,0.176206,ICD10_C16,0.011,Neoplasms
2,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000656,0.000000,0.000000,0.000219,...,0.000000,0.254821,0.7452,8.546847e-53,3.799884e-11,0.000006,0.014349,ICD10_F31,0.007,Mental and behavioural disorders
3,random_negative,DL,0.000000,0.000000,0.133333,0.001277,0.009579,0.333333,0.001064,0.003192,...,0.526385,0.534168,0.4659,8.675835e-04,3.994504e-02,0.077062,0.207102,ICD10_I10,0.014,Diseases of the circulatory system
4,random_negative,DL,0.000000,0.000000,0.500000,0.000639,0.001277,1.000000,0.000426,0.000426,...,0.769303,0.904041,0.0960,1.185224e-03,1.526198e-01,0.314758,0.628549,ICD10_D83,0.099,Diseases of the blood and blood-forming organs...
5,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000640,0.000000,0.000000,0.000213,...,0.000000,0.479204,0.5208,4.075252e-37,5.218041e-08,0.000228,0.058588,ICD10_L20,0.0,Diseases of the skin and subcutaneous tissue
6,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000639,0.000000,0.000000,0.000213,...,0.000000,0.658604,0.3414,1.397737e-24,1.683139e-05,0.004103,0.159575,ICD10_C23,0.0,Neoplasms
7,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.003205,0.200000,0.000214,0.001068,...,0.400021,0.518926,0.4811,6.607034e-11,2.533648e-03,0.022877,0.140521,ICD10_N17,0.149,Diseases of the genitourinary system
8,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000639,0.000000,0.000000,0.000213,...,0.000000,0.641935,0.3581,9.566305e-26,9.840993e-06,0.003137,0.145659,ICD10_M34,0.0,Diseases of the musculoskeletal system and con...
9,random_negative,DL,0.000000,0.040000,0.120000,0.001927,0.016057,0.360000,0.001927,0.005352,...,0.545582,0.444813,0.5551,8.698519e-03,4.229662e-02,0.071735,0.182159,ICD10_I25,0.0,Diseases of the circulatory system
10,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000645,0.000000,0.000000,0.000215,...,0.000000,0.688625,0.3114,1.750460e-22,4.425130e-05,0.006652,0.187960,ICD10_J45,0.057,Diseases of the respiratory system
11,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000638,0.000000,0.000000,0.000213,...,0.000000,0.193478,0.8065,4.420731e-57,5.263049e-12,0.000002,0.008973,ICD10_I26,0.116,Diseases of the circulatory system
12,random_negative,DL,0.000000,0.000000,0.250000,0.000640,0.002559,0.750000,0.000640,0.000853,...,0.714364,0.751024,0.2491,1.043614e-06,3.001745e-02,0.128245,0.401113,ICD10_K44,0.13,Diseases of the digestive system
13,random_negative,DL,0.000000,0.032787,0.163934,0.006579,0.040132,0.508197,0.006798,0.013377,...,0.629503,0.608247,0.3922,2.962943e-03,4.108555e-02,0.094247,0.273956,ICD10_C50,0.0,Neoplasms
14,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.005158,0.250000,0.000430,0.001719,...,0.454540,0.515102,0.4849,3.349753e-13,8.434955e-04,0.015153,0.148692,ICD10_G30,0.014,Diseases of the nervous system
15,random_negative,DL,0.000000,0.000000,1.000000,0.000639,0.000639,1.000000,0.000213,0.000213,...,0.769257,0.931070,0.0690,1.526167e-05,1.086730e-01,0.329656,0.692448,ICD10_C43,0.0,Neoplasms
16,random_negative,DL,0.000000,0.000000,0.285714,0.001277,0.004470,0.428571,0.000638,0.001489,...,0.588318,0.568957,0.4311,1.111392e-06,2.420895e-02,0.099506,0.294256,ICD10_F90,0.0,Mental and behavioural disorders
17,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001922,0.333333,0.000213,0.000640,...,0.526364,0.468904,0.5311,1.442376e-13,1.118367e-03,0.019315,0.141890,ICD10_N04,0.104,Diseases of the genitourinary system
18,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.004487,0.285714,0.000427,0.001495,...,0.487805,0.488947,0.5111,3.151688e-09,4.272380e-03,0.028345,0.159308,ICD10_N46,0.0,Diseases of the genitourinary system
19,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000639,0.000000,0.000000,0.000213,...,0.000000,0.326928,0.6731,9.334442e-48,3.874005e-10,0.000020,0.023362,ICD10_D57,0.072,Diseases of the blood and blood-forming organs...
20,random_negative,DL,0.000000,0.000000,0.153846,0.002572,0.016720,0.384615,0.002143,0.005571,...,0.561919,0.526285,0.4738,1.229393e-03,3.555037e-02,0.084310,0.232034,ICD10_I50,0.0,Diseases of the circulatory system
21,random_negative,DL,0.111111,0.222222,0.444444,0.002558,0.005754,0.555556,0.001065,0.001918,...,0.649487,0.678889,0.3212,1.197960e-01,2.448774e-01,0.316105,0.435602,ICD10_C18,0.058,Neoplasms
22,random_negative,DL,0.000000,0.000000,0.500000,0.000643,0.001285,1.000000,0.000428,0.000428,...,0.769299,0.849769,0.1503,5.277639e-07,3.233034e-02,0.141885,0.475221,ICD10_G40,0.202,Diseases of the nervous system
23,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001914,0.333333,0.000213,0.000638,...,0.526369,0.563880,0.4362,5.614061e-14,9.259680e-04,0.017707,0.158705,ICD10_J62,0.062,Diseases of the respiratory system
24,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001914,0.000000,0.000000,0.000638,...,0.000000,0.251250,0.7487,1.282811e-47,2.983589e-10,0.000014,0.017065,ICD10_C53,0.012,Neoplasms
25,random_negative,DL,0.000000,0.111111,0.222222,0.001287,0.005792,0.333333,0.000644,0.001931,...,0.526348,0.573483,0.4266,1.415235e-02,8.026550e-02,0.121823,0.254363,ICD10_I42,0.032,Diseases of the circulatory system
26,random_negative,DL,0.000000,0.100000,0.100000,0.000639,0.006386,0.500000,0.001064,0.002128,...,0.625125,0.621488,0.3786,1.236074e-02,7.751375e-02,0.149419,0.336320,ICD10_F72,0.0,Mental and behavioural disorders
27,random_negative,DL,0.000000,0.000000,0.500000,0.000643,0.001286,0.500000,0.000214,0.000429,...,0.625035,0.749662,0.2504,9.279845e-07,3.564357e-02,0.134089,0.374989,ICD10_G20,0.057,Diseases of the nervous system
28,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000639,0.000000,0.000000,0.000213,...,0.000000,0.695094,0.3050,4.956081e-22,5.449786e-05,0.007382,0.194691,ICD10_G10,0.037,Diseases of the nervous system
29,random_negative,DL,0.000000,0.000000,1.000000,0.000640,0.000640,1.000000,0.000213,0.000213,...,0.769276,0.904183,0.0959,2.018101e-07,4.572528e-02,0.213835,0.599822,ICD10_J80,0.101,Diseases of the respiratory system
30,random_negative,DL,0.000000,0.000000,0.142857,0.000649,0.004540,0.285714,0.000432,0.001513,...,0.487810,0.538682,0.4614,4.030755e-03,7.174179e-02,0.116317,0.234627,ICD10_E11,0.003,"Endocrine, nutritional and metabolic diseases"
31,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001281,0.000000,0.000000,0.000427,...,0.000000,0.410683,0.5893,2.198531e-41,6.156005e-09,0.000077,0.039310,ICD10_L40,0.219,Diseases of the skin and subcutaneous tissue
32,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.000644,0.000000,0.000000,0.000215,...,0.000000,0.630769,0.3693,1.586937e-26,6.869182e-06,0.002621,0.137001,ICD10_N80,0.038,Diseases of the genitourinary system
33,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001277,0.500000,0.000213,0.000426,...,0.625060,0.557233,0.4428,2.299224e-16,4.261740e-04,0.014608,0.166727,ICD10_G91,0.0,Diseases of the nervous system
34,random_negative,DL,0.000000,0.000000,0.125000,0.000640,0.005122,0.375000,0.000640,0.001707,...,0.555587,0.495845,0.5042,9.530384e-08,7.512976e-03,0.034529,0.166116,ICD10_K51,0.181,Diseases of the digestive system
35,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001277,0.500000,0.000213,0.000426,...,0.625035,0.409477,0.5905,3.605277e-15,7.392763e-04,0.019226,0.169705,ICD10_M41,0.071,Diseases of the musculoskeletal system and con...
36,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001278,0.000000,0.000000,0.000426,...,0.000000,0.545475,0.4546,4.392887e-22,3.055852e-05,0.003937,0.116807,ICD10_N97,0.159,Diseases of the genitourinary system
37,random_negative,DL,0.000000,0.125000,0.250000,0.001346,0.005384,0.250000,0.000449,0.001795,...,0.454540,0.494572,0.5055,1.751237e-02,8.989294e-02,0.129388,0.227083,ICD10_F20,0.0,Mental and behavioural disorders
38,random_negative,DL,0.000000,0.000000,0.107143,0.001913,0.017857,0.250000,0.001488,0.005952,...,0.454487,0.484588,0.5154,2.999377e-04,3.166938e-02,0.065126,0.172815,ICD10_F01,0.0,Mental and behavioural disorders
39,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001283,0.500000,0.000214,0.000428,...,0.625050,0.662284,0.3378,4.433344e-15,7.706235e-04,0.019869,0.208763,ICD10_M32,0.212,Diseases of the musculoskeletal system and con...
40,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.003240,0.400000,0.000432,0.001080,...,0.571487,0.614313,0.3858,3.677224e-11,2.343271e-03,0.026584,0.203494,ICD10_E66,0.002,"Endocrine, nutritional and metabolic diseases"
41,random_negative,DL,0.000000,0.000000,0.250000,0.000639,0.002554,0.250000,0.000213,0.000851,...,0.454556,0.608130,0.3919,2.641771e-05,4.002600e-02,0.101690,0.254696,ICD10_G24,0.0,Diseases of the nervous system
42,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001283,0.000000,0.000000,0.000427,...,0.000000,0.339917,0.6601,2.847129e-35,7.011474e-08,0.000188,0.038581,ICD10_N18,0.106,Diseases of the genitourinary system
43,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.002554,0.000000,0.000000,0.000851,...,0.000000,0.483911,0.5161,5.746764e-28,1.384334e-06,0.000830,0.074879,ICD10_C81,0.176,Neoplasms
44,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001278,0.500000,0.000213,0.000426,...,0.625035,0.550323,0.4497,2.679786e-08,1.753449e-02,0.093635,0.291904,ICD10_I63,0.115,Diseases of the circulatory system
45,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.002554,0.500000,0.000426,0.000851,...,0.625045,0.551363,0.4487,1.311175e-14,5.813693e-04,0.014562,0.161243,ICD10_G43,0.042,Diseases of the nervous system
46,random_negative,DL,0.000000,0.000000,0.000000,0.000000,0.001921,0.333333,0.000213,0.000640,...,0.526332,0.535049,0.4650,1.244208e-20,5.412864e-05,0.005707,0.137951,ICD10_I70,0.084,Diseases of the circulatory system
47,random_negative,DL,0.000000,0.052632,0.157895,0.001934,0.012250,0.368421,0.001504,0.004083,...,0.551261,0.571301,0.4288,4.077251e-02,7.492286e-02,0.117543,0.260817,ICD10_C67,0.009,Neoplasms

In [ ]:
# full_fused_2019.to_csv('/itf-fi-ml/shared/users/ziyuzh/svm/results/single_weighted_fused_2019_bag.csv',index=False)

In [ ]:
# full_fused_2019=pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/results/single_weighted_fused_2019_bag.csv')

In [23]:
# full_fused_2019 = pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/results/weighted_fused_2019.csv')
full_fused_2019 = full_fused_2019[['method', 'para', 'auroc','bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30', 'weights','disease', 'category']]

In [24]:
full_fused_2019['para'].unique()

array(['DL'], dtype=object)

In [25]:
# full_fused_2019['weights'] = full_fused_2019['weights'].astype(float)
full_fused_2019 = full_fused_2019.round(3)
# full_fused_2019 = full_fused_2019.rename(columns={'para': 'feature'})
feature_order = ['DL']
 

# feature_order = ['uniport_ppi_2017', 'uniport_bio', 'uniport_esm', 'uniport_seq', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# feature_order = ['uniport_ppi_2019', 'uniport_bio', 'uniport_esm', 'uniport_seq', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# # Define the custom order for 'feature'
# feature_order = ['ppi_2019', 'bioconcept', 'esm2', 'uniport', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# feature_order = ['ppi_2017', 'gene2vec', 'esm2', 'uniport', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# Convert 'feature' to a categorical type with that order
full_fused_2019['para'] = pd.Categorical(full_fused_2019['para'], categories=feature_order, ordered=True)

# Now sort by 'disease' first, then 'feature' by the custom order
full_fused_2019 = full_fused_2019.sort_values(by=['disease', 'para'])

In [26]:
target_cols = ['auroc', 'bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30']

# Define alternating background colors per disease
base_colors = ['#ffdddd', '#dbf7db']
diseases = full_fused_2019['disease'].unique()
disease_color_map = {disease: base_colors[i % len(base_colors)] for i, disease in enumerate(diseases)}

def combined_style(df):
    styles = pd.DataFrame('', index=df.index, columns=df.columns)

    # Add background color row-wise
    for idx, row in df.iterrows():
        bg_color = disease_color_map[row['disease']]
        styles.loc[idx, :] = f'background-color: {bg_color};'

    # Highlight max in each group & each target column
    for category, group in df.groupby('disease'):
        for col in target_cols:
            max_val = group[col].max()
            max_indices = group[group[col] == max_val].index
            for idx in max_indices:
                styles.loc[idx, col] += ' color: red; font-weight: bold;'
    
    return styles

In [27]:
# Build mapping for background colors per disease
# full_fused_2019['para'] = full_fused_2019['para'].str.replace('ppi_2016', 'ppi_2017', regex=False)
full_fused_2019_disease = full_fused_2019.style.apply(combined_style, axis=None)


full_fused_2019_disease

In [ ]:
# abnormal = ['ICD10_C43','ICD10_N80','ICD10_N18', 'ICD10_G24', 'ICD10_E66', 'ICD10_D83', 'ICD10_C50']
# results = fused_2019[~fused_2019['disease'].isin(abnormal)]
# fused_2019

In [28]:
# fused_2019['para'] = fused_2019['para'].str.replace('ppi_2016', 'ppi_2017', regex=False)
results = fused_2019
mapped_results = {icd: find_disease_category(icd) for icd in results['disease']}
results['category'] = results['disease'].map(mapped_results)

collected_dfs = []
disease_num = dict()
for category in results['category'].unique().tolist():
    subdf = results[results['category'] == category].copy()
    subdf = subdf.drop(columns='weights')
    sum_df = create_summary(subdf, ['method', 'para'], fused=True)
    sum_df['category'] = category
    collected_dfs.append(sum_df)
    disease_num[category] = len(subdf) / 2

final_df = pd.concat(collected_dfs, ignore_index=True)

category_order = final_df.groupby('category', observed=True)['auroc_mean'].mean().sort_values(ascending=False).index.tolist()
final_df['category'] = pd.Categorical(final_df['category'], categories=category_order, ordered=True)

show_df = final_df.sort_values(by=['category', 'auroc_mean'], ascending=[True, False]) \
    .loc[:, final_df.columns.str.contains('method|para|auroc_mean|bedroc_1_mean|bedroc_5_mean|bedroc_10_mean|bedroc_30_mean|category', case=False)] \
    .round(3) \
    .rename(columns=lambda x: x.replace('_mean', ''))

# feature_order = ['ppi_2017', 'gene2vec', 'esm2', 'uniport', 
#                  'linear_fused', 'geo_fused','weighted_linear_fused','weighted_geo_fused']

# Convert 'feature' to a categorical type with that order
show_df['para'] = pd.Categorical(show_df['para'], categories=feature_order, ordered=True)

# Now sort by 'disease' first, then 'feature' by the custom order
show_df = show_df.sort_values(by=['category', 'para'])

# Define alternating background colors per disease
base_colors = ['#ffdddd', '#dbf7db']


# Build mapping for background colors per disease
category = show_df['category'].unique()
color_map = {disease: base_colors[i % len(base_colors)] for i, disease in enumerate(category)}

In [29]:
target_cols = ['auroc', 'bedroc_1', 'bedroc_5', 'bedroc_10', 'bedroc_30']

def combined_style2(df):
    styles = pd.DataFrame('', index=df.index, columns=df.columns)

    # Add background color row-wise
    for idx, row in df.iterrows():
        bg_color = color_map[row['category']]
        styles.loc[idx, :] = f'background-color: {bg_color};'

    # Highlight max in each group & each target column
    for category, group in df.groupby('category'):
        for col in target_cols:
            max_val = group[col].max()
            max_indices = group[group[col] == max_val].index
            for idx in max_indices:
                styles.loc[idx, col] += ' color: red; font-weight: bold;'
    
    return styles

# Apply combined style
styled_df = show_df.style.apply(combined_style2, axis=None)
styled_df
# styled_df.to_excel("/itf-fi-ml/shared/users/ziyuzh/svm/results/styled_2019_fused_weighted.xlsx", engine="openpyxl", index = False)

/tmp/ipykernel_3370025/1906553618.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for category, group in df.groupby('category'):

In [14]:
with pd.ExcelWriter('/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_fused.xlsx', engine='openpyxl') as writer:
    styled_df.to_excel(writer, sheet_name='category', index=False)
    full_fused_2019_disease.to_excel(writer, sheet_name='disease', index=False)

/tmp/ipykernel_3370025/1906553618.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for category, group in df.groupby('category'):

In [ ]:
### choose gamma
### entire dataset, get kernel (dist matrix)
### calculate nearest dist sum
### 2 * sum = gamma

In [ ]:
######## weighted kernel, weights comes from the biology pathway overlap
# 1. train / val split (no-time-cut) cross validation??
# 2. set threshold -200
# 3. pathway enrichment of predicted FPs and TPs
# 4. enriched reults similarity (jaccard-sim, Semantics similarity between terms)
# bootstrap bioconcept, gene2vec, uniport, esm2
##### fused only ppi and bioconcept
##### fused * bootstrap_bagging
##### fused 2017

In [ ]:
### hard negative
### low scores in disgenet
### perturb positive to be neg
### simialr disease positive to be positives