In [1]:
import os
import pandas as pd

root1 = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_nn_6_features'
root2 = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_nn_3_features'
out_folder = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_nn_merged'

# Ensure output dir exists
os.makedirs(out_folder, exist_ok=True)

for file_name in os.listdir(root1):
    if 'all' in file_name:
        continue

    file_path1 = os.path.join(root1, file_name)
    file_path2 = os.path.join(root2, file_name)

    # Skip if the counterpart is missing in root2
    if not os.path.isfile(file_path1) or not os.path.isfile(file_path2):
        continue

    df1 = pd.read_csv(file_path1)
    df2 = pd.read_csv(file_path2)
    df2['para'] = df2['para'].replace({
        "DL_early-0-0-0": "DL_early_ppi-0-0-0",
        "DL_mid-0-0-0": "DL_mid_ppi-0-0-0",
        "DL_later_avg-0-0-0": "DL_later_avg_ppi-0-0-0",
        "DL_later_mlp-0-0-0": "DL_later_mlp_ppi-0-0-0"
    })

    df2 = df2[df2['para'] != 'DL_string_id-0-0-0']
    df1 = df1[df1['para'] != 'DL_string_id-0-0-0']


    # Round all numeric columns to 4 decimals
    df1 = df1.copy()
    df2 = df2.copy()
    num_cols1 = df1.select_dtypes(include='number').columns
    num_cols2 = df2.select_dtypes(include='number').columns
    df1[num_cols1] = df1[num_cols1].round(4)
    df2[num_cols2] = df2[num_cols2].round(4)

    # Merge row by row (concatenate) and de-duplicate rows
    df3 = pd.concat([df1, df2], ignore_index=True, sort=False).drop_duplicates()
    # Save
    out_path = os.path.join(out_folder, file_name)
    df3.to_csv(out_path, index=False)

In [2]:
df3

,method,fold,para,top_recall_25,top_recall_300,top_recall_10%,top_precision_10%,max_precision_10%,top_recall_30%,top_precision_30%,...,pm_15%,pm_20%,pm_25%,pm_30%,auroc,rank_ratio,bedroc_1,bedroc_5,bedroc_10,bedroc_30
0,random_negative,1,DL_early-0-0-0,0.0000,0.4737,0.5789,0.0071,0.0123,0.7895,0.0032,...,0.8087,0.7600,0.7471,0.7250,0.8244,0.1761,0.1208,0.3809,0.4718,0.6156
1,random_negative,1,DL_mid-0-0-0,0.0000,0.2105,0.5263,0.0064,0.0123,0.7895,0.0032,...,0.8087,0.7985,0.7600,0.7250,0.7783,0.2221,0.0457,0.2123,0.3313,0.5533
2,random_negative,1,DL_uniport_ppi_2019-0-0-0,0.0000,0.2632,0.5263,0.0064,0.0123,0.6842,0.0028,...,0.8087,0.7600,0.7328,0.6955,0.6976,0.3027,0.0678,0.2247,0.3274,0.5034
3,random_negative,1,DL_ppi_2019_dw_40-0-0-0,0.1053,0.2632,0.6316,0.0077,0.0123,0.6842,0.0028,...,0.8208,0.7744,0.7328,0.6955,0.7416,0.2587,0.1574,0.3562,0.4598,0.5903
4,random_negative,1,DL_uniport_bio-0-0-0,0.0000,0.1579,0.4211,0.0052,0.0123,0.6842,0.0028,...,0.7600,0.7251,0.7168,0.6955,0.7206,0.2797,0.0573,0.1932,0.2802,0.4596
5,random_negative,1,DL_uniport_seq-0-0-0,0.0000,0.1053,0.4211,0.0052,0.0123,0.7895,0.0032,...,0.7378,0.7437,0.7328,0.7250,0.7711,0.2293,0.0482,0.1362,0.2274,0.4590
6,random_negative,1,DL_uniport_esm-0-0-0,0.0000,0.1053,0.3158,0.0039,0.0123,0.7368,0.0030,...,0.7600,0.7437,0.6988,0.7110,0.7459,0.2545,0.0786,0.1646,0.2455,0.4476
7,random_negative,1,DL_diffusion_2019_2-0-0-0,0.0000,0.2105,0.6842,0.0084,0.0123,0.7895,0.0032,...,0.8208,0.7871,0.7471,0.7250,0.7955,0.2049,0.0523,0.2801,0.4147,0.6066
8,random_negative,1,DL_later_avg-0-0-0,0.1053,0.3684,0.6842,0.0084,0.0123,0.7368,0.0030,...,0.8208,0.7744,0.7328,0.7110,0.7922,0.2082,0.1664,0.3842,0.4935,0.6321
9,random_negative,1,DL_later_mlp-0-0-0,0.1579,0.2632,0.6842,0.0084,0.0123,0.7895,0.0032,...,0.8208,0.7744,0.7471,0.7250,0.7959,0.2045,0.1637,0.3561,0.4741,0.6318
10,random_negative,1,DL_early_ppi-0-0-0,0.0526,0.2105,0.6316,0.0077,0.0123,0.6842,0.0028,...,0.8087,0.7744,0.7328,0.6955,0.7538,0.2465,0.0980,0.2962,0.4146,0.5733
11,random_negative,1,DL_mid_ppi-0-0-0,0.0000,0.1579,0.4737,0.0058,0.0123,0.7895,0.0032,...,0.7948,0.7600,0.7168,0.7250,0.7596,0.2407,0.0704,0.2185,0.3152,0.5143
14,random_negative,1,DL_diffusion_2019_2-0-0-0,0.0000,0.1579,0.6316,0.0077,0.0123,0.7895,0.0032,...,0.8315,0.7985,0.7600,0.7250,0.7941,0.2062,0.0347,0.2302,0.3767,0.5977
15,random_negative,1,DL_later_avg_ppi-0-0-0,0.1053,0.2632,0.6316,0.0077,0.0123,0.7895,0.0032,...,0.8208,0.7744,0.7328,0.7250,0.7848,0.2156,0.1537,0.3630,0.4723,0.6231
16,random_negative,1,DL_later_mlp_ppi-0-0-0,0.1053,0.3158,0.6316,0.0077,0.0123,0.7895,0.0032,...,0.8208,0.7985,0.7600,0.7250,0.7976,0.2028,0.1453,0.3411,0.4569,0.6283

In [10]:
import os
import pandas as pd

root1 = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_df_test_pos_to_neg_mid'
root2 = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_df_test_pos_to_neg_ppi_mid'
out_folder = '/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_df_correct_mid'

# Ensure output dir exists
os.makedirs(out_folder, exist_ok=True)

for file_name in os.listdir(root1):
    if 'all' in file_name:
        continue

    file_path1 = os.path.join(root1, file_name)
    file_path2 = os.path.join(root2, file_name)

    # Skip if the counterpart is missing in root2
    if not os.path.isfile(file_path1) or not os.path.isfile(file_path2):
        continue

    df1 = pd.read_csv(file_path1)
    df2 = pd.read_csv(file_path2)
    df2['para'] = df2['para'].replace({
        "linear_fused-0-0-0": "linear_fused_ppi-0-0-0",
        "geo_fused-0-0-0": "geo_fused_ppi-0-0-0"
    })


    # Round all numeric columns to 4 decimals
    df1 = df1.copy()
    df2 = df2.copy()
    num_cols1 = df1.select_dtypes(include='number').columns
    num_cols2 = df2.select_dtypes(include='number').columns
    df1[num_cols1] = df1[num_cols1].round(4)
    df2[num_cols2] = df2[num_cols2].round(4)

    # Merge row by row (concatenate) and de-duplicate rows
    df3 = pd.concat([df1, df2], ignore_index=True, sort=False).drop_duplicates()
    # df3 = df3[df3['para'] != 'DL_mid-0-0-0']
    # Save
    out_path = os.path.join(out_folder, file_name)
    df3.to_csv(out_path, index=False)

In [11]:
df3

,method,fold,para,top_recall_25,top_recall_300,top_recall_10%,top_precision_10%,max_precision_10%,top_recall_30%,top_precision_30%,...,pm_15%,pm_20%,pm_25%,pm_30%,auroc,rank_ratio,bedroc_1,bedroc_5,bedroc_10,bedroc_30
0,random_negative,1,uniport_ppi_2019-0-0-0,0.1579,0.4211,0.6842,0.0084,0.0123,0.6842,0.0028,...,0.8208,0.7744,0.7328,0.6955,0.7336,0.2667,0.3086,0.4918,0.5653,0.6418
1,random_negative,1,ppi_2019_dw_40-0-0-0,0.2105,0.5263,0.6842,0.0084,0.0123,0.6842,0.0028,...,0.8208,0.7744,0.7328,0.6955,0.7684,0.2319,0.3439,0.5338,0.5975,0.6624
2,random_negative,1,diffusion_2019-0-0-0,0.3158,0.4737,0.4737,0.0058,0.0123,0.6842,0.0028,...,0.7787,0.7251,0.7168,0.6955,0.7448,0.2556,0.3397,0.4215,0.4540,0.5447
3,random_negative,1,uniport_bio-0-0-0,0.0526,0.2632,0.5263,0.0064,0.0123,0.7368,0.0030,...,0.8087,0.7744,0.7328,0.7110,0.7436,0.2567,0.1084,0.2876,0.3896,0.5552
4,random_negative,1,uniport_seq-0-0-0,0.0526,0.1053,0.4211,0.0052,0.0123,0.7368,0.0030,...,0.7787,0.7600,0.7328,0.7110,0.7789,0.2215,0.0565,0.1764,0.2817,0.4999
5,random_negative,1,uniport_esm-0-0-0,0.0000,0.1053,0.4737,0.0058,0.0123,0.6842,0.0028,...,0.7948,0.7437,0.7328,0.6955,0.7422,0.2581,0.0263,0.1477,0.2545,0.4674
6,random_negative,1,linear_fused-0-0-0,0.2105,0.5263,0.6842,0.0084,0.0123,0.6842,0.0028,...,0.8208,0.7744,0.7328,0.6955,0.7697,0.2307,0.3439,0.5242,0.5888,0.6601
7,random_negative,1,geo_fused-0-0-0,0.1053,0.5263,0.6842,0.0084,0.0123,0.6842,0.0028,...,0.8208,0.7744,0.7328,0.6955,0.7865,0.2139,0.3024,0.5049,0.5764,0.6582
11,random_negative,1,linear_fused_ppi-0-0-0,0.2105,0.5263,0.6842,0.0084,0.0123,0.6842,0.0028,...,0.8208,0.7744,0.7328,0.6955,0.7452,0.2551,0.3312,0.5195,0.5870,0.6524
12,random_negative,1,geo_fused_ppi-0-0-0,0.2632,0.5789,0.6842,0.0084,0.0123,0.6842,0.0028,...,0.8208,0.7744,0.7328,0.6955,0.7751,0.2253,0.3669,0.5447,0.6028,0.6683