In [18]:
import pandas as pd
import os
import pickle
import numpy as np

In [2]:
results = pd.read_csv('/itf-fi-ml/shared/users/ziyuzh/svm/results/all_metrics_1and2percent.csv')

In [3]:
results.head(2)

,disease,setting,method,bio_sim_300,bio_sim_150,category,top_recall_150,succ_150,w_recall_150,top_recall_300,succ_300,w_recall_300,bedroc_150,bedroc_300,auroc
0,ICD10_C16,df_gnn_occsvm_pred,early_fused,0.197614,0.220574,Neoplasms(8),0.20,1,0.198171,0.32,1,0.332317,0.105634,0.178621,0.861021
1,ICD10_C16,df_gnn_occsvm_pred,early_fused_ppi,0.161484,0.170398,Neoplasms(8),0.28,1,0.326220,0.40,1,0.472561,0.206987,0.287726,0.890605

In [4]:
results['setting'].unique(),results['method'].unique(),results['category'].unique()

(array(['df_gnn_occsvm_pred', '2019_occ_deep_svd_pred/pred.pkl',
        '2019_nn_all_pred', '2019_rf_renamed_pred', '2019_mf_add_pred',
        'graphsage', 'gcn'], dtype=object),
 array(['early_fused', 'early_fused_ppi', 'late_fused', 'late_fused_ppi',
        'ppi_emb_n2v', 'ppi_emb_dw', 'ppi_emb_df', 'literature_emb',
        'seq_emb_esm', 'seq_emb_port', 'mid_linear_fused', 'mid_geo_fused',
        'mid_linear_fused_ppi', 'mid_geo_fused_ppi', 'occ_svm',
        'uniport_ppi_2019', 'mid_fused', 'mid_fused_ppi'], dtype=object),
 array(['Neoplasms(8)', 'Mental and behavioural disorders(5)',
        'Diseases of the circulatory system(7)',
        'Diseases of the respiratory system(3)',
        'Diseases of the nervous system(7)',
        'Endocrine, nutritional and metabolic diseases(2)',
        'Diseases of the musculoskeletal system and connective tissue(3)',
        'Diseases of the blood and certain disorders(3)',
        'Diseases of the genitourinary system(6)',
        'Diseases of the digestive system(2)',
        'Diseases of the skin and subcutaneous tissue(2)'], dtype=object))

In [5]:
results[(results['setting']=='2019_rf_renamed_pred')&(results['method']=='seq_emb_port')&(results['category']=='Diseases of the blood and certain disorders(3)')]

,disease,setting,method,bio_sim_300,bio_sim_150,category,top_recall_150,succ_150,w_recall_150,top_recall_300,succ_300,w_recall_300,bedroc_150,bedroc_300,auroc
407,ICD10_D66,2019_rf_renamed_pred,seq_emb_port,0.106542,0.127119,Diseases of the blood and certain disorders(3),1.0,1,1.0,1.0,1,1.0,9.499617e-01,9.746598e-01,0.999681
1155,ICD10_D83,2019_rf_renamed_pred,seq_emb_port,0.114943,0.113990,Diseases of the blood and certain disorders(3),0.0,0,0.0,0.0,0,0.0,3.817734e-59,4.370416e-30,0.118576
1223,ICD10_D57,2019_rf_renamed_pred,seq_emb_port,0.036649,0.040724,Diseases of the blood and certain disorders(3),0.0,0,0.0,0.0,0,0.0,1.437816e-53,3.791855e-27,0.242052

In [6]:
results[(results['setting']=='2019_rf_renamed_pred')&(results['method']=='seq_emb_port')&(results['category']=='Diseases of the blood and certain disorders(3)')].mean(numeric_only=True)

bio_sim_300       0.086045
bio_sim_150       0.093944
top_recall_150    0.333333
succ_150          0.333333
w_recall_150      0.333333
top_recall_300    0.333333
succ_300          0.333333
w_recall_300      0.333333
bedroc_150        0.316654
bedroc_300        0.324887
auroc             0.453436
dtype: float64

In [12]:
results[(results['method']=='seq_emb_port')&(results['category']=='Diseases of the blood and certain disorders(3)')][['disease', 'setting', 'method', 'bio_sim_300', 'top_recall_150','top_recall_300', 'bedroc_150',
       'bedroc_300', 'auroc']]

,disease,setting,method,bio_sim_300,top_recall_150,top_recall_300,bedroc_150,bedroc_300,auroc
383,ICD10_D66,df_gnn_occsvm_pred,seq_emb_port,0.125000,1.0,1.0,9.211488e-01,9.597649e-01,0.999490
398,ICD10_D66,2019_nn_all_pred,seq_emb_port,0.058824,0.0,0.0,2.874061e-03,5.361027e-02,0.963627
407,ICD10_D66,2019_rf_renamed_pred,seq_emb_port,0.106542,1.0,1.0,9.499617e-01,9.746598e-01,0.999681
1131,ICD10_D83,df_gnn_occsvm_pred,seq_emb_port,0.099291,0.0,0.0,5.466430e-58,1.711447e-29,0.164049
1146,ICD10_D83,2019_nn_all_pred,seq_emb_port,0.151639,0.0,0.0,6.273287e-10,1.771063e-05,0.447871
1155,ICD10_D83,2019_rf_renamed_pred,seq_emb_port,0.114943,0.0,0.0,3.817734e-59,4.370416e-30,0.118576
1199,ICD10_D57,df_gnn_occsvm_pred,seq_emb_port,0.038202,0.0,0.0,1.476547e-11,3.842587e-06,0.844995
1214,ICD10_D57,2019_nn_all_pred,seq_emb_port,0.049738,0.0,0.0,1.026942e-09,3.204593e-05,0.871361
1223,ICD10_D57,2019_rf_renamed_pred,seq_emb_port,0.036649,0.0,0.0,1.437816e-53,3.791855e-27,0.242052
1701,ICD10_D66,2019_mf_add_pred,seq_emb_port,0.074012,1.0,1.0,6.365225e-01,7.978236e-01,0.997192
1833,ICD10_D83,2019_mf_add_pred,seq_emb_port,0.039625,0.0,0.0,1.817940e-35,3.015039e-18,0.443880
1845,ICD10_D57,2019_mf_add_pred,seq_emb_port,0.027933,0.0,0.0,3.586824e-02,1.893891e-01,0.979316
1989,ICD10_D66,graphsage,seq_emb_port,0.117845,1.0,1.0,2.210851e-01,4.701969e-01,0.990620
2121,ICD10_D83,graphsage,seq_emb_port,0.089015,0.0,0.0,1.611579e-62,1.269301e-31,0.115591
2133,ICD10_D57,graphsage,seq_emb_port,0.031579,0.0,0.0,6.671039e-10,2.582835e-05,0.868680
2277,ICD10_D66,gcn,seq_emb_port,0.051087,0.0,1.0,6.719565e-02,2.592212e-01,0.983217
2409,ICD10_D83,gcn,seq_emb_port,0.056838,0.0,0.0,5.214371e-27,5.106081e-14,0.539648
2421,ICD10_D57,gcn,seq_emb_port,0.022206,0.0,1.0,1.799083e-01,4.241560e-01,0.989339

In [16]:
file_path = "/itf-fi-ml/shared/users/ziyuzh/svm/results/2019_mf_add_pred/ICD10_D57_pred.pkl"

with open(file_path, "rb") as f:
    data = pickle.load(f)

In [17]:
data.keys()

dict_keys(['true_label', 'test_genes', 'train_pos_genes', 'uniport_ppi_2019', 'ppi_2019_dw_40', 'uniport_bio', 'uniport_seq', 'uniport_esm', 'diffusion_2019_pca'])

In [19]:

y_true = np.array(data['true_label'])
y_pred = np.array(data['uniport_seq'])

# Step 1: sort indices by prediction score (descending)
sorted_indices = np.argsort(-y_pred)

# Step 2: create rank array
ranks = np.empty_like(sorted_indices)
ranks[sorted_indices] = np.arange(1, len(y_pred) + 1)

# Step 3: get ranks of positive samples
positive_ranks = ranks[y_true == 1]

print(positive_ranks)

[325]

In [ ]:
"/itf-fi-ml/shared/users/ziyuzh/svm/results/statistic/permutation_models_category.csv"